### ISSUE TITLE
unwanted name attribute from asdf NDArrayType

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#110]
There appears to happen some unlucky attribute propagation when reading from asdf `ndarray` -> `pint.Quantity` -> `xarray.DataArray` which makes the following fail:

~~~python
ts = TimeSeries(data=Q_([40.0,20.0], "V"),time=Q_([0.0,10.0],"s"))
data = weldx.asdf.utils._write_read_buffer({"root":ts})
data["root"] == ts
>>> False
~~~
Both `TimeSeries` have identical values but `==` fails because `xarray.DataArray.identical` checks every attribute including `DataArray.name`

When reading from the ASDF file in this case the name attribute gets erroneously applied:
~~~python
print(ts.data_array.name)
>>> None
print(data["root"].data_array.name)
>>> core/ndarray
~~~

The problem occurs because when creating a `pint.Quantity` directly from an ndarray it actually gets constructed from the asdf `NDArrayType` which apparently carries `.name='core/ndarray'`
This propagates over to the `pint.Quantity` and finally `xarray.DataArray`.

Here is a quick fix for the `TimeSeries` class https://github.com/BAMWelDX/weldx/pull/104/commits/1dd1f23ef76c59cbc8c198d00bdf97d049e3c3f7 but we should be aware of the issue and discuss how to handle this in general.

**Comment by marscher** [comment]
Ain't an issue any more.

**Comment by CagtayFabry** [comment]
I think we fixed this in the `TimeSeries` asdf implementation?
but the general problem should still persist.

One possible idea could be to adapt asdf implementation of our quantity to remove the attribute.

**Comment by CagtayFabry** [comment]
cref https://github.com/BAMWelDX/weldx/pull/364#discussion_r655330492

**Comment by vhirtham** [comment]
So reopen?

**Comment by CagtayFabry** [comment]
yes I think I'd like to run some more tests until finally closing this one

**Comment by marscher** [comment]
Sorry, if this caused extra work now. I just ran the attached snippet and it didn't showed the described behavior any more.

**Comment by CagtayFabry** [comment]
it's good to keep in mind, I'll have to think of a proper snipped for debugging

**Comment by marscher** [comment]
I guess this has something to do with attributes being discarded if set to None during serialization. A name of an xarray got set to None, to prevent the automatic derivation from the underlying array (NDArrayType of asdf has a name attribute), will be lost.

Probably there are only workarounds to this behavior until we decide we set the name attribute of an xarray to None explicitly and allow its serialization as well.

**Comment by marscher** [comment]
the linked pr fixed this issue.
