### ISSUE TITLE
using schema-dependencies

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#111]
For GMAW processes it could be helpful to restrict schemas based on the process type string using [schema-dependencies](https://json-schema.org/understanding-json-schema/reference/object.html#schema-dependencies) (if possible)

**Comment by marscher** [comment]
The word "dependency" does not occur once in the linked document. Is this still relevant? If so, please re-open.

**Comment by CagtayFabry** [comment]
> The word "dependency" does not occur once in the linked document. Is this still relevant? If so, please re-open.

I was probably looking at [pattern properties](https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties) but I don't think this is relevant any more (and I am not sure if or how that is supported by asdf)
