### ISSUE TITLE
update tutorial notebook header levels

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#118]
to play nice with `sphinx` and `nbsphinx` we should be consistent with markdown header levels in our notebooks:

- every notebook has a single top `# H1` Header in the first cell. This will become the page header in the sphinx documentation
- all following chapters should *at most* be `## H2` (we will get multiple page links for a single notebook otherwise)

We can see about the best toctree depth to use from here

**Comment by vhirtham** [comment]
This can be closed, right?
