### ISSUE TITLE
Further CSM enhancements

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#122]
- When merging two CSM instances it is currently required, that both instances have one identically named coordinate system. While this requirement makes sense, it should be supported that the same coordinate system can have different names in both CSM instances. In this case, one has to specify which names are referring to the same coordinate system. An example where this might be useful is a tool that can be connected to different mount points. In the tools CSM, the coordinate system might just be named "flange", while the object it should be connected to has several flanges named "flange 1", "flange 2" , etc. Keep in mind, that the original name must be stored so that the merged system can be restored with  `get_subsystem` or `unmerge`

- Enhance plot function by highlighting subsystems (colored frame) and adjust the general appearance (font sizes, arrows shouldn't collide with the font, etc)

- turn all getter functions that do not have any parameters into properties

**Comment by CagtayFabry** [comment]
some notes:
- I would like arrows in CSM plots to only have arrowheads pointing in the direction the LCS was originally defined
- split into seperate issues (for smaller PRs :wink: )

**Comment by CagtayFabry** [comment]
since this is still open can you please review what is still relevant and split into single issues @vhirtham ?

**Comment by CagtayFabry** [comment]
beside

> turn all getter functions that do not have any parameters into properties

I think we can close this

**Comment by vhirtham** [comment]
> beside
> 
> > turn all getter functions that do not have any parameters into properties
> 
> I think we can close this

I am fine with closing this one. The getter things are more cosmetic. The merge functionality might be interesting but seems not to be needed ATM.
