### ISSUE TITLE
enable interactive widgets in sphinx docs

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#127]
Test if this works for our widget examples:
https://ipywidgets.readthedocs.io/en/latest/embedding.html#embedding-widgets-in-the-sphinx-html-documentation

**Comment by CagtayFabry** [comment]
I think we can close this for now and use binder for interactive sessions?

**Comment by vhirtham** [comment]
Agreed. But we should definitely add a binder section in the documentation so that the reader is aware of this option.

**Comment by CagtayFabry** [comment]
closed after #188
