### ISSUE TITLE
Coordinate system orientation

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#13]
All methods of the `LocalCoordinateSystem` except the `construct_from_euler` method provide an option to create a positive or negative oriented coordinate system (right-handed, left-handed). This should also be possible for the  `construct_from_euler` method. (branch: coordinate_system_manager)

Also, we should reevaluate if the current implementation is correct. Do all transformations of LCS and CSM work correctly if positive and negative orientations are mixed?

**Comment by vhirtham** [comment]
Not sure if this is still relevant. I have no clue how commonly used left-handed coordinate systems are. Do we want to close this one for now?

**Comment by CagtayFabry** [comment]
yeah I think we will just sort this out if it ever pops up 😉
