### ISSUE TITLE
Additional checks during pull requests

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#135]
for PRs that target master or the release branch:
- check if the version number was increased
- check if the changelog was updated

The checks should not be required to merge the PR. Their purpose is to remind us of those things before we merge.

**Comment by CagtayFabry** [comment]
- version numbers are handled via git tags so this should work anyway (we should only generate stable docs from tags)
- for other checks we could implement [PR templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) ([example](https://github.com/hgrecco/pint/blob/master/pull_request_template.md))
