### ISSUE TITLE
ReadTheDocs has limited build time

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#136]
The build time for free projects is limited to 15 minutes ([Source](https://docs.readthedocs.io/en/latest/builds.html)). Checking one of the [latest successful builds](https://readthedocs.org/projects/weldx/builds/11952302/) reveals that we are already getting quite close to this limit (772 seconds ~ 13 minutes). I expect us to exceed this limit in the near future if we add more jupyter notebook tutorials. So what are our options?

- As stated on the linked page, one can ask for additional build time. Not sure if they will do that, especially when they see, that the pandas theme we use somehow circumvents the embedding of adds.
- [Buying a business plan](https://docs.readthedocs.io/en/latest/commercial/index.html). Pricing starts at [50$ per month](https://readthedocs.com/pricing/).
- Publish somewhere else (Github pages)
- Reduce build time. There are two possible approaches I think we can do this for now:
    - Use a dedicated Conda environment. Currently, we are using the weldx environment which already takes several minutes to build. If we can reduce the necessary packages to a minimum, this might free some resources. However, this will only work if we skip running the notebooks
    - Using a dedicated documentation branch. The GitHub action that currently builds the docs pushes all generated files to that branch and triggers the RTD build (only for the master branch).  
- [See this link](https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html)

**Comment by CagtayFabry** [comment]
cref https://github.com/BAMWelDX/weldx/pull/238#issuecomment-783383061

**Comment by CagtayFabry** [comment]
the current build time sits around ~630s with the recent tweaks, so enough breathing room for now? 😃
