### ISSUE TITLE
Publish WelDX docker container using GitHub packages

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#141]
[GitHub packages](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages) offers the possibility to publish docker container images (Container-registry). We should provide a docker container with the latest WelDX version installed that automatically starts a Jupyter-lab server. This way, potential users don't need to bother with the Anaconda installation and can use WelDX in a browser by simply downloading and running the docker image.

**Comment by CagtayFabry** [comment]
I think the current binder setup and conda install is simple enough, so close?
