### ISSUE TITLE
use pint wrapping for classes without quantity support

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#144]
I think we should make use of `pint` wrapping for automatic unit conversion for classes that do not support pint internally (yet)
https://pint.readthedocs.io/en/stable/performance.html#a-safer-method-wrapping 

Looks like the simplest way to support units for the current geometry package. (Example: wrap geometry class inputs to always convert to `mm`)

**Comment by vhirtham** [comment]
Seems like a good temporary solution. I will already add it to some classes that I currently use while writing the geometry class tutorial.
