### ISSUE TITLE
Coordinate systems

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#15]
- [x] time depency `LocalCoordinateSystem` (xarray)
- [x] generic dimensions `LocalCoordinateSystem` (xarray)
- [x] time depency `CoordinateSystemManager`
- [x] interpolation 
- [x] update tutorial 
- [x] rename origin to coordinates
- [x] rename basis to orientation
- [x] evalute if `CoordinateSystemManager` `interp_time` and `interp_time_like` should have an optional parameter (`list_of_edges`) to aplly the interpolations only to a selected list of coordinate systems
- [x] add time dependency to factories
- [x] enable direct construction of `LocalCoordinateSystem` classes by the `CoordinateSystemManager` when adding coordinate systems. Either use a single function that takes a string to switch between construction methods or write a wrapper for each constructor

**Comment by CagtayFabry** [comment]
We should discuss supporting both [pandas.DateTimeIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) as well as [pandas.TimeDeltaIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.TimedeltaIndex.html)
