### ISSUE TITLE
missing list formatting from notebook markdown cells in sphinx doc

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#160]
List items created in markdown cells do not seem to correctly show up in the sphinx docs.

Example:
notebook: https://github.com/BAMWelDX/weldx/blob/master/tutorials/welding_example_01_basics.ipynb
sphinx: https://weldx.readthedocs.io/en/latest/tutorials/welding_example_01_basics.html

**Comment by vhirtham** [comment]
Try adding 2 more whitespaces after the dash. I can remember Codacy once complained about 1 space being wrong or not portable for list item

~~~ markdown
wrong formatted list
- item 1
- item 2

correct formatted list
-   item 1
-   item 2
~~~ 

Maybe you also need an additional blank line between the text and the list.

**Comment by CagtayFabry** [comment]
I finally figured this out: we were missing a newline that is required before each list.

Have a look at the `nbsphinx` documentation: https://nbsphinx.readthedocs.io/en/latest/markdown-cells.html ([raw](https://raw.githubusercontent.com/spatialaudio/nbsphinx/7c60c2e79acfeb16290f363818f0021433d39b03/doc/markdown-cells.ipynb)) 

```gfm
wrong formatted list
- item 1
- item 2
1234
 
correct formatted list

- item 1
- item 2

1234
```
This applies to all list types (numbered etc.)
