### ISSUE TITLE
Clear jupyter notebook outputs

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#169]
Every time we rerun a Jupyter notebook we get rather large git diffs because the cached outputs vary slightly. This is a little bit annoying to review and also bloats the repository size over time. Since the official documentation is now online, we do not need the rendered outputs here on GitHub anymore. So my suggestion would be to strip the notebooks of all outputs before pushing them. I had just a quick look into [this article](https://medium.com/somosfit/version-control-on-jupyter-notebooks-6b67a0cf12a3) so I can't tell if it is helpful but maybe we can automatize this.

**Comment by CagtayFabry** [comment]
I suggest setting up a git pre-push hook for this

https://githooks.com/
