### ISSUE TITLE
Update developers documentation about time data types

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#170]
Just a reminder that this needs some additional work and some corrections

**Comment by CagtayFabry** [comment]
maybe we can revisit this in light of #284 ? Define some package level type aliases for time types?

**Comment by marscher** [comment]
Don't we have such aliases already for timedeltaindices etc.?

**Comment by marscher** [comment]
Are you saying we should document the type alias, so it shows up in the docs?

**Comment by vhirtham** [comment]
> Are you saying we should document the type alias, so it shows up in the docs?

We have a "developers documentation" that was removed from the official doc and moved into the wiki. [This](https://github.com/BAMWelDX/weldx/wiki/Time-Data) is the page Cagtay is referring to.

**Comment by marscher** [comment]
On 4/1/21 9:46 AM, vhirtham wrote:
>> Are you saying we should document the type alias, so it shows up in the docs?
> 
> We have a "developers documentation" that was removed from the official doc and moved into the wiki. [This](https://github.com/BAMWelDX/weldx/wiki/Time-Data) is the page Cagtay is referring to.
> 

Ahh I should have taken a look into this weeks ago :-) Thanks for the link!

**Comment by vhirtham** [comment]
Well, there is probably a lot of stuff outdated. Hence Cagtays comment ;)

**Comment by vhirtham** [comment]
Obsolete with PR #433
