### ISSUE TITLE
CSM notebook plot

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#196]
Another interesting option for graph plotting in Notebooks:
https://github.com/QuantStack/ipycytoscape
https://blog.jupyter.org/interactive-graph-visualization-in-jupyter-with-ipycytoscape-a8828a54ab63

check out on binder: https://mybinder.org/v2/gh/QuantStack/ipycytoscape/stable?filepath=examples (`examples/NetworkX Example.ipynb`

Styling the nodes/edges might be easier with this?

**Comment by CagtayFabry** [comment]
We should test how this looks in a static sphinx notebook first

Also would be nice to disable mouse interactions

**Comment by vhirtham** [comment]
We can keep this in mind for the case that the current graph plotting isn't enough anymore.

**Comment by CagtayFabry** [comment]
we should open an issue here https://github.com/BAMWelDX/weldx-widgets in that case
