### ISSUE TITLE
Sphinx documentation

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#2]
## General procedure

Follow the workflow described below for every task that involves coding:

0. (optional) Ask if a task isn't clear ;)
1. Create a new branch
2. Commit regularly. It is better to use multiple small commits until you have finished a task than a single one at the end.
3. Create a pull request to the master branch and ask for a review
4. Apply changes if requested until the pull request is approved.
5. If the pull request is approved, merge your code into the master branch, and restart this procedure with the next task

---

## List of tasks

The following checklist contains a number of substeps that should be processed one after each other to get a general understanding of Shinx:

- [x] Fork the example repository and create a minimal working sphinx setup. Go through the `conf.py` file and adjust the already present options to your needs.
- [x] Create some extra pages with minimal content ("Hello World") and link them together. Make sure they appear in the table of content and that they can be opened.
- [x] Add support for markdown files and integrate a markdown file that is depicted correctly in the final HTML document.
https://www.sphinx-doc.org/en/master/usage/markdown.html
- [x] convert all docstrings from ReStructuredText to the numpy docstring format
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#google-vs-numpy
- [x] Enable support for numpy style docstrings with the `napoleon` extension
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
- [x] Link your example repository to `readthedocs` and configure everything so that your example documentation is available online. This should be just some configuration steps on GitHub and the `readthedocs` homepage. `readthedocs` will automatically build the documentation from the master branch of the GitHub repository for you. 
- [x] Read about [GitHub actions](https://help.github.com/en/actions) and add an extra ob to the action of the example repository that prints "Hello World"
- [x] Remove the Hello World job and configure the action so that it builds the documentation and uploads it to `readthedocs`. Follow the Guide on the `readthedocs` homepage that tells you how to manually upload documentations to the site. Building the documentation manually gives us more flexibility.
- [x] Configure the documentation to use the `pandas_sphinx_theme`
- [x] Read about the `autosummary` feature of Sphinx and activate it for the example repository. Make sure that every function of the example Python files appears in the documentation. It is okay for now if not every piece of the function doc-strings is shown. To fix this will be the next step. It might be necessary to add extra plugins to Sphinx 
- [x]  Read about `autosummary` templates and create them for the repository. Modify them so that every function/class has an own documentation page where every item of the doc-strings appears.
- [x] Add Jupyter-Notebooks to the documentation
https://nbsphinx.readthedocs.io/

---

[Link to the example repository](https://github.com/Nikitha-ramasetti/python_project_template)

**Comment by CagtayFabry** [comment]
This repo has a nice template using conda CI + github artifacts for sphinx docs

https://github.com/crusaderky/python_project_template

**Comment by CagtayFabry** [comment]
I have updated and rearranged the list with some additional items, please have a look @vhirtham
