### ISSUE TITLE
Tags might get replaced by schema URI

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#203]
[click me and see -> Drop the tag: URI scheme and use http:// URIs for YAML tagging](https://github.com/asdf-format/asdf-standard/wiki/2.0.0-roadmap#drop-the-tag-uri-scheme-and-use-http-uris-for-yaml-tagging)

This would basically solve the issue I had before when I said I see no point in having 2 different identifiers for the same thing. Anyways, let's see when it will be implemented. I think they already started the transition with the `http` URI as key for the resource mapping.

**Comment by marscher** [comment]
We have this now in asdf-2.8. Follow up issue #368
