### ISSUE TITLE
move to python 3.9 as default

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#216]
I would like to transition to 3.9 featureset early, mostly because of the new dict operators (more user friendly)
https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators

we should also try support for the new type hints
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

**Comment by CagtayFabry** [comment]
what are your thoughts on this @marscher ?

it does not follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) but we already have some Python 3.7+ only code afaik and since this is very much alpha state I would switch to more stable support later (building on 3.9).

**Comment by marscher** [comment]
We are in the luxury situation that we can freely decide to choose a very recent Python version, so in my opinion we should use it. I recall the painful days when I had support Python2 and 3, which greatly limited the usage of cutting edge language features.

On February 23, 2021 12:57:28 PM UTC, Cagtay Fabry <notifications@github.com> wrote:
>what are your thoughts on this @marscher ?
>
>it does not follow [NEP
>29](https://numpy.org/neps/nep-0029-deprecation_policy.html) but we
>already have some Python 3.7+ only code afaik and since this is very
>much alpha state I would switch to more stable support later (building
>on 3.9).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/BAMWelDX/weldx/issues/216#issuecomment-784182421

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marscher** [comment]
It seems like Python3.9 is not yet supported by the backend used by KISA master (https://github.com/pythonnet/pythonnet). I guess we should consider supporting Python 3.8 for little while.

**Comment by CagtayFabry** [comment]
oh that's too bad, I will revert this to be >=3.8
