### ISSUE TITLE
SciPy-1.6 version breaks WXRotation

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#226]
The new SciPy release is not compatible with our `WXRotations` object. Some interfaces changed and some functions seem to be removed or renamed.

**Comment by marscher** [comment]
I think this has already been addressed upstream, but is not yet released https://github.com/scipy/scipy/commit/1d4e9df17b3f8ae2e6b27621c2cde9cf1df6c9a6

cref: https://github.com/asdf-format/asdf/issues/916

**Comment by marscher** [comment]
Upstream issue (scipy) is fixed, now we have to way for a release :)

**Comment by vhirtham** [comment]
@marscher They released version 2.7.3 recently that includes the fix

**Comment by marscher** [comment]
https://github.com/asdf-format/asdf/issues/916#issuecomment-786161684 and re-opened the issue

**Comment by CagtayFabry** [comment]
we will do a patch release to unpin scipy in the requirements after their next release 🚀

**Comment by CagtayFabry** [comment]
it appears scipy has assigned [the fix](https://github.com/scipy/scipy/pull/13598) to their `1.7.0` milestone which could some time to release

Should we ask to include this into `1.6.2` @marscher ? IIRC there are no breaking changes introduced with this fix right?

**Comment by marscher** [comment]
On 3/15/21 1:47 PM, Cagtay Fabry wrote:
> it appears scipy has assigned [the fix](https://github.com/scipy/scipy/pull/13598) to their `1.7.0` milestone which could take some time to release
> 
> Should we ask to include this into `1.6.2` @marscher ? IIRC there are no breaking changes introduced with this fix right?
> 
No it does not brake any previous assumptions, so I can try asking for 
it. Thanks for looking into it.
