### ISSUE TITLE
cleanup package distribution files

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#245]
the current build/distribution contains almost the entire git repo and is very bloated

should clean this up using `setup.cfg` or `MANIFEST.in` configuration

**Comment by marscher** [comment]
I've used the manifest mostly to prune things from the dist. There are already some defaults, like excluding .git and python cache files, but this should be expanded (e.g. jupyter checkpoints etc.).

**Comment by CagtayFabry** [comment]
I will draft something up for you to look over @marscher

**Comment by CagtayFabry** [comment]
updated `MANIFEST.in` in #246 @marscher
