### ISSUE TITLE
Binding of schema to/from Python class

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#249]
Having to access a deserialized asdf file via dictionary keys works fine, but is not especially user/programmer friendly, as there is no auto-completion and documentation (like of properties/accessor methods)

For example:
``` python
process = data["process"]
process["welding_process"]
...
```

Additionally if the schema changes, scripts accessing the dictionary directly are likely to fail. 
So we should think of wrapping the schemas in Python classes/objects to avoid breaking compatibility on schema changes. There are automated ways of doing so, but we should discuss, what features are desirable before sticking to a library. We can even decide of doing it manually, but this would introduce another maintenance job keeping the schemas and classes in sync.

**Comment by CagtayFabry** [comment]
any tools/libraries you know that might be helpful?
I think in most cases creating a simple `dataclass` from an ASDF schema should be sufficient (and rather straight forward with basic features), this could be done at runtime or generated upon changes/releases

**Comment by marscher** [comment]
https://stackoverflow.com/questions/6578986/how-to-convert-json-data-into-a-python-object I assume the same thing is possible for YAML. However doing it on the fly has the downside, that it has no documentation.

**Comment by CagtayFabry** [comment]
I guess YAML/ASDF -> Python dataclass for our use case is simple enough, with some ASDF tools we should be able to quickly generate quite clean code files

An older jinja template can be found [here ](https://github.com/BAMWelDX/weldx/blob/0.2.2/weldx/asdf/templates/asdf_dataclass.py.jinja)
with some of the new ASDF tools this might be worth revisiting, certainly a useful tool for sometime in the future (I image a simple web interface/editor -> ASDF schema -> python class to be very user friendly)

If we just want to have .attr acces something simpler like your link might suffice

Maybe this is relevant as well? https://github.com/konradhalas/dacite

**Comment by CagtayFabry** [comment]
also just leaving this here for reference https://stackoverflow.com/questions/53376099/python-dataclass-from-a-nested-dict

**Comment by CagtayFabry** [comment]
if we just want to have an attribute like access styles maybe [attrdict](https://pypi.org/project/attrdict/) is handy
