### ISSUE TITLE
enable doctests

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#250]
We should run doctests within pytest to ensure the examples given in the documentation are always functional. This should be very easy to enable, since it is only a flag passed to pytest. Eventually some doctests are already out of sync.

**Comment by CagtayFabry** [comment]
we currently do not have many code examples in the docstrings but would be nice to couple with doctest if we add more

**Comment by marscher** [comment]
We can re-open this, once we have the proper amount of doctests.
