### ISSUE TITLE
default line length 120 chars??

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#257]
Honestly I've never seen 88 chars before in any project. I think 120 should be pretty safe nowadays (e.g. see discussion here https://stackoverflow.com/questions/17319422/how-do-i-set-the-maximum-line-length-in-pycharm)

**Comment by vhirtham** [comment]
88 is the default value of the black code-formatter. From [The black documentation](https://black.readthedocs.io/en/stable/the_black_code_style.html):

>You probably noticed the peculiar default line length. Black defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, 90-ish seems like the wise choice.
>
>If you’re paid by the line of code you write, you can pass --line-length with a lower number. Black will try to respect that. However, sometimes it won’t be able to without breaking other rules. In those rare cases, auto-formatted code will exceed your allotted limit.
>
>You can also increase it, but remember that people with sight disabilities find it harder to work with line lengths exceeding 100 characters. It also adversely affects side-by-side diff review on typical screen resolutions. Long lines also make it harder to present code neatly in documentation or talk slides.
>
>If you’re using Flake8, you can bump max-line-length to 88 and forget about it.

If I am working at home,  the laptop screen doesn't have much more space for side-by-side views. So 120 would be a problem. But I am open to change it if both of you think it is necessary.

**Comment by marscher** [comment]
Thanks for the explanation. Working on small screens is actually a very solid argument. Let's keep the setting. I was just curious about the 88 chars setting, since it also violates classic PEP8.
