### ISSUE TITLE
asdffile wrapper discussion

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#271]
We should wrap the most common functionalities needed by users/KISA project.
This far from complete lists contains:
- creating file handles 
- reading the tree
- updating the tree
- adding history information (we should discuss here as well, what would be useful)
- validate against a schema

**Comment by CagtayFabry** [comment]
Thanks for opening this up
I think we had some ideas related to the quality-standards as well, maybe we can collect them here

maybe the wrapper could also expose a dynamic attribute like interface to the tree like discussed in #249 ?

**Comment by marscher** [comment]
I thought quality standards would be covered by validating the file against a schema, right?
The file wrapper should expose the tree wrapper as well :)

**Comment by CagtayFabry** [comment]
> I thought quality standards would be covered by validating the file against a schema, right?
> The file wrapper should expose the tree wrapper as well :)

It's more a drop-in replacement of existing schemas so having information about the QS used/passed will be very convenient

**Comment by CagtayFabry** [comment]
here is a small example on how to extract all objects from the `TaggedDict` returned via #338 that match a specific tag pattern:
The thing to look out for is that the default exit function will remove the `_tag` information
```python
from collections.abc import Mapping, Sequence, Set
from pathlib import Path

import asdf
from boltons.iterutils import remap

from weldx.asdf.util import get_yaml_header

p = Path("./scripts/single_pass_weld_example.asdf")
d = get_yaml_header(p, parse=True)


def tagged_exit(path, key, old_parent, new_parent, new_items):
    # print('exit(%r, %r, %r, %r, %r)'
    #       % (path, key, old_parent, new_parent, new_items))
    ret = new_parent
    if isinstance(new_parent, asdf.tagged.Tagged):  # pass on tag information
        new_parent.update(new_items)
        new_parent._tag = old_parent._tag
    elif isinstance(new_parent, Mapping):
        new_parent.update(new_items)
    elif isinstance(new_parent, Sequence):
        vals = [v for i, v in new_items]
        try:
            new_parent.extend(vals)
        except AttributeError:
            ret = new_parent.__class__(vals)  # tuples
    elif isinstance(new_parent, Set):
        vals = [v for i, v in new_items]
        try:
            new_parent.update(vals)
        except AttributeError:
            ret = new_parent.__class__(vals)  # frozensets
    else:
        raise RuntimeError("unexpected iterable type: %r" % type(new_parent))
    return ret


def get_all_tags(tree, tag):
    all_tags = []

    def visit(path, key, value):
        if tag in value._tag:
            all_tags.append(value)
        return False

    remap(tree, visit=visit, reraise_visit=False, exit=tagged_exit)

    return all_tags


res = get_all_tags(d["process"], tag="quantity")
print(res)
```

This could be a usefull functionality provided by the wrapper (we should add this into `weldx` anyway soon)
