### ISSUE TITLE
use type aliases

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#272]
We should consider using [type aliases](https://docs.python.org/3.8/library/typing.html#type-aliases) (note we're on py3.8) in some modules with more complex type annotations

especially some common larger unions like `Union[pd.TimedeltaIndex, pd.DateTimeIndex, xr.DataArray]` could become simplified and more explicit where the same inputs are allowed

this will also reduce the work to be done once we switch to python 3.9 type hints

**Comment by vhirtham** [comment]
Totally support this. Maybe we can also put some aliases into the weldx namespace like CSM ant LCS
