### ISSUE TITLE
create static LCS instance with time axis

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#281]
The following code creates a static `LCS` instance even though a time axis with length 2 is set. The time dependency is simply dropped.
```python
import pandas as pd
import weldx

lcs = weldx.LocalCoordinateSystem(
    coordinates=[0, 0, 1], time=pd.timedelta_range(start="0s", end="20s", periods=2)
)
lcs

>>> <LocalCoordinateSystem>
>>> Dimensions:      (c: 3, v: 3)
>>> Coordinates:
>>>   * c            (c) <U1 'x' 'y' 'z'
>>>   * v            (v) int32 0 1 2
>>> Data variables:
>>>     coordinates  (c) float64 0.0 0.0 1.0
>>>     orientation  (v, c) float64 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0
```

I am not sure if this should be allowed or raise a warning/an exception.
What do you think @vhirtham ?

The case is also not mentioned in the documentation.

**Comment by vhirtham** [comment]
As far as I can remember, we decided to ignore time values for non-time-dependent systems. However, throwing an exception won't hurt. I'll fix it

**Comment by CagtayFabry** [comment]
I think a warning should be enough, no need to break anything 👼

**Comment by vhirtham** [comment]
> I think a warning should be enough, no need to break anything 👼
> We should mention this case in the docstring of `LCS`

Don't think that something will break. I'll test an exception. If there is any failure in the tests, I'll turn it into a warning and postpone it 😛
