### ISSUE TITLE
deprecate rotation_matrix_* functions

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#294]
I think we can deprecate the `transformations.rotation_matrix_*` functions in favor of `WXRotation.as_matrix` to allow more input options and clean up the API a bit

They are mostly used for testing

**Comment by marscher** [comment]
For the aid of deprecating funtions, at least in my experience, a deprecation class/function decorator is very useful. It shows a warning indicating that the called object is deprecated and can be turned into a an error via the warnings module to clean up all usages within the code base. Users will just see the warning for a couple of versions and can adopt their code accordingly. 

Back to topic, I agree that these functions are a indeed a duplication of features and should be replaced by scipy Rotations.

**Comment by vhirtham** [comment]
Since we are the only users so far, I think we can just remove it. However, having a deprecated decorator is probably a nice thing for the future. I'll add one...

**Comment by CagtayFabry** [comment]
yes this should only "break" internal code so removing should be fine :)
we can redefine these in the tests directly to simplify refactoring
