### ISSUE TITLE
Measurement.Data.data.data.data

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#297]
The data class data has the field data and name, but the since xarrays support the name attribute as well, I wonder why we have this kind of duplication? It makes code working with Measurements look strange, since we need to access data twice to obtain the actual xarray. Further if I want to access the raw data it gets even worse :)
We could just define a measurement to directly contain a "plain", although pretty high-level, xarray, right?

**Comment by vhirtham** [comment]
I am currently rewriting the `MeasurementChain` related stuff in the context of #63. Removing this "construct" is also on the agenda... even though there is no such thing as too much data 😄

**Comment by CagtayFabry** [comment]
yes it can get confusing quickly, I think we should try to stick to existing naming conventions if possible (so `.data` should only be an ndarray-like the way it is for xarray for example). We could find a more fitting attribute name for xarray objects as well

We should discuss a rework of the measurment module soon, maybe you can share your Ideas here or in #63 @vhirtham ?

**Comment by vhirtham** [comment]
This should basically be solved with PR #326 . However, there are some occasions where we get a `data.data`, for example in the `TimeSeries`. This always occurs if a `data` function returns an xarray type and you want to have the raw data. Not sure if we want to go any further, but I think it should be okay.

**Comment by vhirtham** [comment]
> maybe rename instances that access xarray objects to something else besides data like `dataarray`, `variable` or similar? and try to keep it consistent for different classes

Seems reasonable

**Comment by CagtayFabry** [comment]
please review if still relevant after latest PRs @vhirtham
