### ISSUE TITLE
weldx.asdf.util.get_yaml_header doesn't work with AsdfFile

### ISSUE THREAD

**Issue by Devmawi** [BAMWelDX/weldx#307]
Try to get the yaml header of a weldx file and got an exception:

``` python

new_asdf_file = asdf.open("vgroove.asdf")
yaml_header = weldx.asdf.util.get_yaml_header(new_asdf_file)

# Exception has occurred: TypeError
# expected str, bytes or os.PathLike object, not AsdfFile
#  File "D:\Documents\dev\python\kisa-weldx-examples\asdf_file_handling.py", line 26, in <module>
#    yaml_header = weldx.asdf.util.get_yaml_header(new_asdf_file)
```

weldx version = 0.3.1
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

See the full example under: 

[kisa-weldx-examples/asdf_file_handling.py](https://github.com/Devmawi/kisa-weldx-examples/blob/6a1f494af1b694b6e5188d2e720e45e052e978c6/asdf_file_handling.py#L26)

**Comment by marscher** [comment]
Hi Devmawi,

according to the documentation you should pass a file name to the get_header function. This makes sense, because the asdf.open() function already reads in all the meta-data and runs validation and so forth (e.g. creates a heavy-weight object).

https://letmegooglethat.com/?q=weldx+get_yaml_header

**Comment by Devmawi** [comment]
Who can read is better off:

```
def get_yaml_header(file) -> str:  # pragma: no cover
    """Read the YAML header part (excluding binary sections) **OF** an ASDF file.

    Parameters
    ----------
    file
        filename, ``pathlib.Path`` or ``BytesIO`` buffer **OF** ASDF file
```

Thank you for your prompt reply.
