### ISSUE TITLE
Perform some search engine optimization for docs

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#309]
Currently the documentation is hard to find on engines like google, duckgosearch, bing etc.
One has to enforce the inclusion of the term "weldx" by using quotation marks. Eventually we should somehow highlight this more.

**Comment by marscher** [comment]
cref #307

**Comment by marscher** [comment]
It seems the version number is currently not avail on RTD although the package gets installed.

**Comment by CagtayFabry** [comment]
good catch, I wonder why this happens..

> It seems the version number is currently not avail on RTD although the package gets installed.

**Comment by CagtayFabry** [comment]
I one way would be to just include `setuptools_scm` in the docs requirement and directly run
```python
from setuptools_scm import get_version
version = get_version(root='..', relative_to=__file__)
```
in `conf.py`

**Comment by marscher** [comment]
This is a good solution. Thanks!

**Comment by marscher** [comment]
Hold on, do we have setuptools_scm installed on RTD?

**Comment by marscher** [comment]
I think it arises from having weldx always imported from the sources root (where the version is undefined; it only gets defined during pip install).

**Comment by CagtayFabry** [comment]
> I think it arises from having weldx always imported from the sources root (where the version is undefined; it only gets defined during pip install).

Ah yes that might be it. Probably because RTD doesn't `pip install -e .`, otherwise the `version.py` file would be created in the source install
see https://github.com/readthedocs/readthedocs.org/pull/4960

How about
```python
try:
    import weldx
except ModuleNotFoundError: # fallback for local use
    sys.path.insert(0, os.path.abspath("../"))
    import weldx
except Exception as ex:
    raise
```

**Comment by CagtayFabry** [comment]
looking good https://github.com/BAMWelDX/weldx/pull/310
