### ISSUE TITLE
tests gets installed to site-packages/tests

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#320]
This is ugly and should not be done. After installing weldx (with pip) you can do the following from any working directory:

``` python -c "import tests.test_geometry" ``` 

Site-packages is globally available for all Python packages and so a very common name like "tests" is confusing as it very unspecific. If we really want to ship the tests (e.g. for the ability to test an installed package instead of a source directory import), we should consider moving the tests into the weldx Python package. 

Or we should restrict the setup.cfg find_packages to the weldx pkg directory.

**Comment by CagtayFabry** [comment]
I also noticed that during the conda test setup

I think we should just move the test scripts from `./tests` to `./weldx/tests` to make things easier (and shipping them should be ok imo)

**Comment by CagtayFabry** [comment]
so move tests to `./weldx/tests`
what do you think @vhirtham ?
