### ISSUE TITLE
pytest windows voes

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#321]
so the windows pytest runs keep failing sporadically with
`_tkinter.TclError: Can't find a usable init.tcl in the following directories: ...`

The ususally pass after a rerun but we should find a way to fix this (even if just disabling multiprocessing for windws runs)

**Comment by CagtayFabry** [comment]
maybe the test setup for plot functions isn't the best either right now

**Comment by marscher** [comment]
mhm, I switched the backend in the tests. See how I set up the matplotlibrc file in pytest.yaml

**Comment by marscher** [comment]
I only applied it for the pip testing though, I guess you're talking about testing in conda now?

**Comment by marscher** [comment]
we could drop a matplotlibrc file next to the recipe and copy it to the test-folder during testing stage.

**Comment by CagtayFabry** [comment]
no the normal github actions keep failing for windows

> 
> 
> I only applied it for the pip testing though, I guess you're talking about testing in conda now?

**Comment by marscher** [comment]
So I was just being tricked by the randomness of failure then. I thought I managed to force matplotlib to use Agg and not TK.

**Comment by marscher** [comment]
not finding a file in the same docker image every 5-10th time is really awkward. We should avoid using tk altogether. I wonder why my matplotlibrc is being ignored.
