### ISSUE TITLE
provide complex schema examples

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#333]
we currently don't have a test for the complex file level schemas in `datamodels`

Maybe we could provide a separte test module that contains functions to generate objects (as pytest fixtures?) to accompany the schemas and be used for tests.
We basically have a script like that allready in `scripts/welding_schema.py` just need to find a good place to put it

**Comment by marscher** [comment]
This is a very good idea. That way we do not have to store asdf files in the repo. I'd suggest to take a copy for the text fixture first, as this script is intended for users, right? If not, we should put it in a weldx.tests.fixtures module.

**Comment by marscher** [comment]
I can give it a shot in PR #328 as I will need a real asdf tree for testing there.

**Comment by marscher** [comment]
fixed by #328
