### ISSUE TITLE
asdf_json_repr name is too technical for end users

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#335]
Suggestions:
file_tree
tree_view
{view|show}_weldx_header

**Comment by vhirtham** [comment]
What about something like `file_tree`, `tree_view`, or similar?

**Comment by CagtayFabry** [comment]
agree, I also forget the function name all the time 😄

**Comment by CagtayFabry** [comment]
I think `tree_view` sounds good, should also be integrated with #271
