### ISSUE TITLE
notebooks should not cd into parent directory

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#342]
I think it is confusing to have this optional instruction for users and is not best practice. Output files will be written (if created), will not be written next to the notebooks, but in the parent, which is unexpected.
We should ensure, that the package is installed prior execution. So we should mention to install (which now should be super easy with pip/conda). On binder it is already installed, right?

**Comment by CagtayFabry** [comment]
yes that is mostly a relic from early dev stages and not very convenient when creating files

I'm ok with simply removing those cells 👍
