### ISSUE TITLE
TimeSeries.interp_time should return a new TimeSeries 

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#346]
Currently, `TimeSeries.interp_time` returns an `xarray.DataArray`. I think it does make more sense to return a new `TimeSeries` instead. If the user really wants to get the underlying xarray object, he can fetch it after the interpolation.

**Comment by CagtayFabry** [comment]
thinking about it I'm not sure if we want to introduce an extra access layer here

An interpolated `TimeSeries` will always be a pure xarray object that imo should not be used like a `TimeSeries`
for example performing another interpolation on already interpolated data

Maybe we should just expose more xarray-like functions to `TimeSeries` (`interp_like` etc.)

or maybe even better (but certainly more complicated)
if we could find a way to register the weldx xarray-accessors to our custom classes that have xarray attributes we could create a unified layer to access xarray properties

**Comment by vhirtham** [comment]
> thinking about it I'm not sure if we want to introduce an extra access layer here
> 
> An interpolated `TimeSeries` will always be a pure xarray object that imo should not be used like a `TimeSeries`
> for example performing another interpolation on already interpolated data

Don't know. The time series a class that describes the behavior of a quantity in time which can be expressed in several ways (discrete or expression). When I interpolate it, I still have a time series. The data is also time-dependent. It is the user's responsibility to not interpolate the same data over and over again. You can do the same with the LCS or the CSM by the way. Also, we could simply introduce an internal interpolation counter and emit a warning when interpolating already interpolated data.

> Maybe we should just expose more xarray-like functions to `TimeSeries` (`interp_like` etc.)

We can simply enhance the capabilities of the class the same way as we did with the LCS 

> or maybe even better (but certainly more complicated)
> if we could find a way to register the weldx xarray-accessors to our custom classes that have xarray attributes we could create a unified layer to access xarray properties

Not sure if I really understand what exactly you have in mind. I think I have a clue, but maybe you can explain it a bit more.

**Comment by CagtayFabry** [comment]
can you give an example where the user would want to have have a `TimeSeries` in return? Similarly if that is wanted, the user could just recreate it (as opposed to accessing the dataarray if required)?
