### ISSUE TITLE
DataArray attributes missing from Dataset ASDF serialization

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#349]
When serializing and reading back a `Dataset`, only the main Dataset attributes get restored. Attributes attached to the individual DataArrays are lost.

```python
da = xr.DataArray(np.arange(10),name="arr1",attrs={"name":"sample data"})
ds = da.to_dataset()
print(ds.arr1.attrs)
ds2 = weldx.asdf.util.write_read_buffer({"ds":ds})["ds"]
print(ds2.arr1.attrs)
>> {'name': 'sample data'}
>> {}
```

**Comment by marscher** [comment]
If xarray is handled by asdf, we should report this upstream, right?

**Comment by marscher** [comment]
ah no, it is our schema. This should be easy to fix.

**Comment by vhirtham** [comment]
> ah no, it is our schema. This should be easy to fix.

Should be, but I remember that there were issues with attributes of substructures before. IRC, those were more of an xarray issue, but I have to take a deeper look into how we currently serialize and reconstruct xarray objects.

**Comment by marscher** [comment]
It seems our custom ASDF types for xarray DataSet and DataArray are not used at all. E.g. the methods to_tree and from_tree are never invoked during serialization.

**Comment by marscher** [comment]
When one serializes a DataSet (containing DataArrays), I would have assumed, that the procedure descent into DataArrays to_tree method. This is not the case. I guess this is the root cause, why the attributes are dropped. 
The DataSets arrays get chopped down into Variables. There we miss the passing of the attributes.
