### ISSUE TITLE
CSM - data belong to subsystems will not be restored correctly

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#365]
After adding the SpatialData serialization to the CSM I checked if the CSM stores if data is added to it by a subsystem during a `merge`. It seems like this is not the case. So restoring the original subsystems using `unmerge` will add no data to them even though it was present before merging.

I think we can treat it as low priority since we do not have any external users yet and we haven't really used the `unmerge` function so far.

**Comment by CagtayFabry** [comment]
good to know, thanks
I agree on your assessment, we should keep this in mind for now

**Comment by vhirtham** [comment]
This is identical to #494 which has already a linked PR. Closing here
