### ISSUE TITLE
Time class

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#367]
We are currently supporting multiple time formats in several places:
- pandas (`DateTimeIndex`, `TimedeltaIndex`, `Timestamp`)
- numpy (time dtypes)
- pint quantities
- xarray structures with "time" and "time_ref" fields

Dealing with time as an additional dimension can actually be quite challenging when trying to enhance, understand or write new code. But also having to deal with those different types turns it into hell. For example, if I just want to compare if the last entry of a time array is less than the first entry of another one I need to figure out if I have relative (time delta) or absolute (dates) values and if they have matching types. Then I need to treat all cases separately. This bloats the code and makes it hard to understand. 

Furthermore, the `time` property of our classes is not consistent regarding its return type. For example, the LCS returns a xarray structure, while the `TimeSeries` returns a `TimedeltaIndex`. The LCS also provides a special method to get time as a quantity to take away the need for type casts from the user.
 
My suggestion is, that we define a `Time` wrapper class, that serves multiple purposes. First, it should be an interface class that is always used when any public function returns a time type. Second, it should be constructable from all the classes that we currently use and provide methods to cast back to all those types like `WXRotation` does for rotations. Lastly, it should provide all the functionalities that we frequently need like calculating time unions and synchronizing reference times.

I would also like to keep time deltas and date times in a single class instead of having two separate classes (possibly three with timestamps). The class method implementations should deal with the compatibility of relative and absolute times so that we do not have to cover it separately every time we deal with time formats.

To make a suggestion of some of the possible interfaces:

~~~ python
class WXTime:
   
    def __init__(
        self,
        time : Union[DateTimeTypes, TimedeltaTypes, TimestampTypes, WXTime],
        time_ref : Union[TimestampTypes, WXTime],
    )

    def to_pandas(self) -> Union[TimedeltaIndex, DateTimeIndex, Timestamp]:

    def to_quantity(self) -> Quantity:

    @property
    def length(self) -> int:

    @property
    def has_reference_time(self) -> bool:

    @property
    def is_timestamp(self) -> bool:
        return self.lengt == 1 and self.has_reference_time

    @property
    def reference_time() -> WXTime:

    @reference_time.setter
    def reference_time( time_ref : Union[TimestampTypes, WXTime]):

    @staticmethod
    def time_union(times = List[WXTime]) -> WXTime:

    def __eq__(self, other:  Union[DateTimeTypes, TimedeltaTypes, TimestampTypes, WXTime]) ->bool:

    def  __le__(self, other:  Union[DateTimeTypes, TimedeltaTypes, TimestampTypes, WXTime]) ->bool:

    def all_close(self, other:  Union[DateTimeTypes, TimedeltaTypes, TimestampTypes, WXTime]) ->bool:

    def overlaps_with(self, other:  Union[DateTimeTypes, TimedeltaTypes, TimestampTypes, WXTime]) ->bool:
~~~

I think this will make our life and of our possible users a lot easier since it bundles all the time-related stuff in one place and unifies the code. What do you think?

**Comment by CagtayFabry** [comment]
I agree that this kind of interface/helper class should make things a lot easier in our codebase. We probably have all those code snippets needed in some point of the code already
it should also simplify things if we decide to change the backend of storing/working with time classes for performance reasons or similar

I'm not sure if we should use this class for all return values, specifically in cases where we already have an `xarray` structure with a `time` coordinate (which I think is the most common).

as an alternative (or extension) maybe we could define interfaces for classes that actually can have a `time` property and work from there?

**Comment by CagtayFabry** [comment]
We should also implement the corresponding `__add__` and `__sub__` functions

**Comment by CagtayFabry** [comment]
can you create a branch and open up a PR only containing the interface definitions for now with `pass` @vhirtham ? I would like to start discussion on the class definition soon and it is easier to follow in that format

for reference it might also be good to take a look at basic pandas index methods and see which of those could be convenient to implement as well (like `min()`, `max()` etc. )

**Comment by vhirtham** [comment]
> can you create a branch and open up a PR only containing the interface definitions for now with `pass` @vhirtham ? I would like to start discussion on the class definition soon and it is easier to follow in that format


I was looking forward to finally start with this class the whole last week. Since all the 0.4.1 issues are finished (I will open the release PR later), we are finally there. I would suggest we proceed as follows:

I create a new branch in the WelDX repo for this issue and add all the interfaces and open a PR to discuss the details as you required. Then I already start drafting some implementations on a separate branch where I think that the behavior is pretty much clear (`__init__` and type-specific accessors like `.quantity`, `.timedeltaindex` etc.) and open a PR targetting the main `weldx.Time` branch. We proceed the same way with the other implementations that we have discussed by then. This way we can review the implementations in small pieces rather than a large chunk.

I also think, that once the class is more or less feature complete, we merge it into master first without using it anywhere. Afterward, we add it class by class using separate branches to keep the mess as small as possible. This is probably a rather large task since time classes are used all over the place.

> for reference it might also be good to take a look at basic pandas index methods and see which of those could be convenient to implement as well (like `min()`, `max()` etc. )

For now, I would like to focus on the functionality that we need for our already implemented classes. This is probably the largest task of the `0.5.0` milestone and there is already a lot to do. I guess the `min()` and `max()` will be required anyways (at least I know where we might need it) but I like to avoid implementing additional features we do not need yet. We can do this later.

> I suggest putting the code into a new module `weldx.time` for now

Agreed. In the long run, I suggest refactoring the core module into multiple files and adding it there since it is such an important and basic class that it feels natural to me to look there first. Also, with the `GenericSeries` on the radar, the core module will need this refactoring anyways at some point 😉

**Comment by CagtayFabry** [comment]
yes, let's have a longer talk tomorrow going over the interfaces before diving into the implementation, we can see how complicated it will get with the individual features

also eager to have that tool ready 🔥 

moving the discussion to #433 from here
