### ISSUE TITLE
restructure asdf directory

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#382]
This is a follow up to #368

A new schema id/tag would look like this:

~~~
id: asdf://weldx.bam.de/weldx/schemas/core/time_series-1.0.0
tag: asdf://weldx.bam.de/weldx/tags/core/time_series-1.0.0
~~~

Apart from the fact, that our previous ids/tags didn't resemble the file structure either, I think it would be nice to change that so that we have

~~~
asdf
|---weldx.bam.de
    |---weldx
        |--- schemas
        |--- tags
~~~

instead of

~~~
asdf
|--- schemas
    |---weldx.bam.de
        |---weldx
|--- tags
    |---weldx.bam.de
        |---weldx
~~~

**Comment by CagtayFabry** [comment]
since the schema definitions should move into their own repository at some point I would suggest using a similar directory setup as `asdf`
This would also flatten the project directories a bit and make it more clear which part of the code resides where, for example:

```
asdf
|--- asdf util code files

tags
|--- weldx.bam.de
    |--- weldx

schemas
|--- weldx.bam.de
     |--- weldx
```

**Comment by CagtayFabry** [comment]
cref #431
