### ISSUE TITLE
Support for string quantities

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#387]
Pint supports strings as a method to create a new Quantity. Functions that use the ureg decorator already convert strings correctly into a quantity, but there are several functions in our packages that do not support it. I think it is a nice feature that makes user code much more readable and is easier to use. So I suggest, that all public interfaces support strings as input method.

**Comment by CagtayFabry** [comment]
can you provide an example?
do you mean to support something like the following
```python
some_function(Q(3,"m"))
some_function("3m")
```

**Comment by vhirtham** [comment]
> can you provide an example?
> do you mean to support something like the following
> 
> ```python
> some_function(Q(3,"m"))
> some_function("3m")
> ```

yes, this is what I mean. If you have more than one Quantity parameter, the function call can look quite messy with all the `Q_`s and parenthesis inside:

~~~
MathematicalExpression("a*x + b", dict(a=Q_(3, "m/s"), b=Q_(24, "m")))
~~~
vs.
~~~
MathematicalExpression("a*x + b", dict(a="3m/s", b="24m"))
~~~

The second version looks much cleaner IMHO

**Comment by CagtayFabry** [comment]
True, I wonder if we can just add another call `Q_(...)` to convert every quantity-like input to quantities in these cases without too much overhead when it already is a quantity?

**Comment by vhirtham** [comment]
> True, I wonder if we can just add another call `Q_(...)` to convert every quantity-like input to quantities in these cases without too much overhead when it already is a quantity?

That is what I have in mind too 😄

**Comment by vhirtham** [comment]
Another rather small benefit is, that the user doesn't have to import `Q_` anymore. Yeah, it's really small, but I can remember scrolling back and forth in notebooks and scripts just because I forgot to import it right from the start.

**Comment by CagtayFabry** [comment]
calling `Q_` again on an existing quantity seems to take around 5us so I think we can just use that in places where we are working with quantities
