### ISSUE TITLE
CSM.__eq__ does not consider attached data

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#395]
This is a really low priority issue since CSM comparison is mainly used in tests, but as the title says, attached data is not considered during the comparison.

**Comment by marscher** [comment]
I wonder why that's the case, because the data is stored in the graph and the nodes are being compared for equality. Shouldn't that cover also the attached data?

**Comment by CagtayFabry** [comment]
With the current layout this should be the case afaik but we might have to look into `graph.__eq__` to see what is actually compared.
Maybe we can add a small test case that is expected to fail (for now)

**Comment by marscher** [comment]
the networkx graph class doesn't implement (override) eq, but rely on finding isomorphisms within both graphs. But this is mathematically not equivalent to equality (exactly the same nodes and topology), right?

So we now just compare the contents of the edges and nodes, if their names are matching. But I think this does not yet cover different topologies, e.g. connections between nodes, they could be named the same way, but interconnect different nodes.
