### ISSUE TITLE
resolve custom schema files in WeldxFile

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#398]
when providing a string as `custom_schema` that does not resolve directly to a file in the directory we could try to find the schema file using our `get_schema_path` function

this would for example allow the following simplification:
```python
wx_file = WeldxFile("./single_pass_weld.weldx", custom_schema="single_pass_weld-1.0.0.schema.yaml")
# instead of
wx_file = WeldxFile("./single_pass_weld.weldx", custom_schema=get_schema_path("single_pass_weld-1.0.0.schema.yaml"))
```

we would just have to try and resolve the schema file before passing it along to asdf here
https://github.com/BAMWelDX/weldx/blob/d50e462cf4804cf17f1a371debaed04ca7e9e34f/weldx/asdf/file.py#L96-L98

what do you think @vhirtham @marscher ?

**Comment by marscher** [comment]
That is is a good idea. I think we should resolve the path inside the class.

**Comment by marscher** [comment]
Just a question in regard to the custom_schema arg of WeldxFile. If the passed tree is empty, a schema is passed and a new file should be created, then we should not validate against the schema, right?

**Comment by marscher** [comment]
Since this would fail instantly without being able to set the data, but I guess this can just be desired.

**Comment by CagtayFabry** [comment]
I would suggest leaving out handling that specific case and see what happens.
You can also provide a schema that only defines optional entries so in that case an empty tree would actually be fine (I guess)
