### ISSUE TITLE
check code dependencies for possible circular imports

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#407]
see here for example https://github.com/BAMWelDX/weldx/pull/366#discussion_r665267182

**Comment by marscher** [comment]
this might become handy: https://github.com/bndr/pycycle

**Comment by vhirtham** [comment]
> this might become handy: https://github.com/bndr/pycycle

Maybe I misunderstood it, but this tool is only helpful if you actually have a circular import problem, e.g. the exception is raised, right?

**Comment by marscher** [comment]
> Maybe I misunderstood it, but this tool is only helpful if you actually have a circular import problem, e.g. the exception is raised, right?

I guess you're right. 

This issue is kind of meta. Once we run into a cyclic reference, there is need to break it. But right know everything works as expected. So I'm closing this one.
