### ISSUE TITLE
compression behavior with WeldxFile

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#417]
When using `WeldxFile` a few inconsistencies can arise regarding the array compression behavior.

Because our custom classes/tags that do not support the lazy loading of `NDarrayType` will always load the `ndarray` data the compression associated with that `ndarray` will get reset, which can increase the filesize unexpectedly when using `WeldxFile`

The following example shows this when running in jupyterlab:
```python
from pathlib import Path

import numpy as np
import xarray as xr

import asdf
import weldx

filename = "demo.asdf"

with asdf.AsdfFile({"data": xr.DataArray(np.ones((1000, 1000)))}) as af:
    af.write_to(filename, all_array_compression="zlib")
    af.close()


print(Path(filename).stat().st_size)
wx_file = weldx.WeldxFile(filename, "rw")
print(Path(filename).stat().st_size)
display(wx_file)
print(Path(filename).stat().st_size)
wx_file.close()

# 12685
# 12685
# 8001014
```
a few things to note:
- opening with `"r"` prevents this issue (but gives the warning)
- only the call to `display` (the interactive json view) recreates the file contents, maybe we can also prevent this here?
- passing a pure `ndarray` in the tree doesn't show this issue (`{"data": np.ones((1000, 1000))}`)

Should be kept in mind when working with files containing large data. @vhirtham @marscher

**Comment by marscher** [comment]
WeldxFile(..., write_kwargs=dict(compression="zlib").display() should do the trick. Perhaps we should set a default for compression to avoid this?

**Comment by CagtayFabry** [comment]
yes nice, thank you!
agree that adding a default compression might be useful in the future, maybe as an option for `WeldxFile` (because it will affect all arrays equally)

We should probably also look into the new compression support from asdf 2.8

**Comment by marscher** [comment]
I was thinking about having a dictionary with default entries, which apply until the user specifies its own setting. I didn't like the write_kwargs and asdffile_kwargs after all. It is too confusing for a user interface.

**Comment by marscher** [comment]
> agree that adding a default compression might be useful in the future, maybe as an option for `WeldxFile` (because it will affect all arrays equally)

So you are saying, that all (important) settings should get a property in the WeldxFile class?

**Comment by CagtayFabry** [comment]
> > agree that adding a default compression might be useful in the future, maybe as an option for `WeldxFile` (because it will affect all arrays equally)
> 
> So you are saying, that all (important) settings should get a property in the WeldxFile class?

not per se, but at the moment I don't really see a way for us to track the individual array compressions but we certainly need to handle that (in an easy way)
so it would make sense to set that on each file e.g. as a property

but adding some other settings as properties might actually be a good interface (also for documentation), what do you think?
`inline_array_threshold` (if that is the new correct config term) also comes to mind if we witch to the local config/context approach later

**Comment by marscher** [comment]
The compression algorithm can be set for every single array as by the current asdf implementation. But I'd guess this is overkill for our case. Actually you can set all these options right now through the asdf_write_kwargs parameter, but this not very user-friendly.

On the other hand we do not want properties for all of these settings to keep a clean interface. Perhaps we provide a config property, which encapsulates the settings (with sane defaults). This config will be used per instance, so there are no side-effects.
Asdf has currently a mixture of values stemming from the config and others originating from input parameters. I hope they will unite this somehow.

**Comment by CagtayFabry** [comment]
Yes, I know about the compression settings for individual arrays.
With the base ASDF implementation it is fine since you keep the link between a numpy (or NDArrayType) array and it's compression settings when opening and closing a file so the compression setting is preserved for each individual file.

Since most of our classes actually use the ndarray data (think xarray) this link gets broken. So just opening a file with individual compression settings, changing something and writing it out again resets these. Hence why for weldx a global setting would make sense (though the user could still try to fiddle with individual array settings on a per array basis using asdf interfaces)

**Comment by marscher** [comment]
There another compression argument is used, currently None. But even if I set it to "input", which should use the "zlib" compression used during initial creation, the array is not being compressed again. So I suspect that this information is lost during within Asdf (e.g. their DataArray handling).

> ```python
> display(wx_file)
> print(Path(filename).stat().st_size)
> wx_file.close()
> ```


>     * only the call to `display` (the interactive json view) recreates the file contents, maybe we can also prevent this here?
 The call to display does an AsdfFile.update() internally to ensure the header is in sync with the current contents. If you have any idea, how we can ensure to display the correct header without calling the asdf serialization, I'd be delighted.

>     * passing a pure `ndarray` in the tree doesn't show this issue (`{"data": np.ones((1000, 1000))}`)
DataArrays seem to be handled differently, compression="input" does not heal this. I guess figuring out the previous compression without the aid of asdf would be tricky and error prone.

**Comment by CagtayFabry** [comment]
> I guess figuring out the previous compression without the aid of asdf would be tricky and error prone.

I agree, that would be way too complex to handle on our part.

> The call to display does an AsdfFile.update() internally to ensure the header is in sync with the current contents. If you have any idea, how we can ensure to display the correct header without calling the asdf serialization, I'd be delighted.

Unfortunately I do not have a solution, the asdf header basically *is* the serialization 😁
but maybe there is a workaround/hack for creating the header without really touching the binary parts:
Ideally we could create a (new) temporary asdf file (basically an updated copy) that does not contain the binary data (to keep the memory footprint small) and simply gather the header information from there. However, I do not know if such a feature or function that only creates the header exists in the `asdf` codebase (I doubt it).

I have one idea how we might be able to 'hack' this behaviour:
since `asdf` now supports custom compression plugins, we could write our own 'dummy-compressor' that simply squashed every binary block into a single (constant) byte. This would basically remove the binary part of the asdf file. Of course the resulting 'file' would be completely broken but we only want to use this for in memory temporary access anyway. (I hope that this 'compression' would come with only minimal performance overhead since we don't even have to read in the real binary parts, simply `return 00`)

To further speed up the serialization process we could also disable the validation steps while creating the temporary copy (not sure we really want that though)

**Comment by marscher** [comment]
> I have one idea how we might be able to 'hack' this behaviour:
> since `asdf` now supports custom compression plugins, we could write our own 'dummy-compressor' that simply squashed every binary block into a single (constant) byte. This would basically remove the binary part of the asdf file. Of course the resulting 'file' would be completely broken but we only want to use this for in memory temporary access anyway. (I hope that this 'compression' would come with only minimal performance overhead since we don't even have to read in the real binary parts, simply `return 00`)
> 
That sounds like a promising idea. It should also be fast. But do we obtain the same header with (fake) compression like the plain non compressed one?

> To further speed up the serialization process we could also disable the validation steps while creating the temporary copy (not sure we really want that though)

I would say, let things fail fast. If the contents break validation, why would we let if fail, after the user decides to use another write operation?

**Comment by CagtayFabry** [comment]
> > I have one idea how we might be able to 'hack' this behaviour:
> > since `asdf` now supports custom compression plugins, we could write our own 'dummy-compressor' that simply squashed every binary block into a single (constant) byte. This would basically remove the binary part of the asdf file. Of course the resulting 'file' would be completely broken but we only want to use this for in memory temporary access anyway. (I hope that this 'compression' would come with only minimal performance overhead since we don't even have to read in the real binary parts, simply `return 00`)
> 
> That sounds like a promising idea. It should also be fast. But do we obtain the same header with (fake) compression like the plain non compressed one?

It should be the same header since the array info (shape etc.) should be taken from the array before compression and just linked to the binary segment using `source`
all relevant info about the binary parts are listed below the header afaik

> 
> > To further speed up the serialization process we could also disable the validation steps while creating the temporary copy (not sure we really want that though)
> 
> I would say, let things fail fast. If the contents break validation, why would we let if fail, after the user decides to use another write operation?

agreed, this would just be for cases where validation is really slow
