### ISSUE TITLE
asdf schema shape validation syntax

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#42]
We should define (and implement) a syntax that allows validation of "shape" properties (such as found in ndarray) against some templates. (updated to use `~` instead of `:`)

```
# syntax
"3"		single dimension of length 3
"~"		single dimension of arbitrary length
"..."	arbitrary number of dimensions of arbitrary length
"(3)"	optional dimension of length 3
"(~)"	optional single dimension of arbitrary length

# true
[3] -> [3]
[2,4,5] -> [2,4,5]
[1,2,3] -> [...]
[1,2,3] -> [1,2,...]
[1,2] -> [1,2,...]
[1,2,3] -> [1,2,~]
[1] -> [1,(~)]
[1] -> [1,...]
[1,2] -> [1,2,(3)]
[1,2,3] -> [1,2,(3)]

# false
[1] -> [1,2]
[1,2] -> [1]
[1,2] -> [3,2]
[1] -> [1,~]
[1,2,3] -> [1,2,(4)]
```

**Comment by CagtayFabry** [comment]
might be relevant: https://medium.com/@nearlydaniel/assertion-of-arbitrary-array-shapes-in-python-3c96f6b7ccb4

**Comment by vhirtham** [comment]
Additionally, the `:` operator can also be used to provide a dimension range -> `1:4`

**Comment by mark141** [comment]
Added a custom validator which uses strings for `shape` and `expected_shape`. I believe all criteria are met. It would be great if someone else would check it out.

The branch:
https://github.com/BAMWelDX/weldx/tree/42_shape_validation

Question: is the `shape` a String or is it something else?

**Comment by CagtayFabry** [comment]
> Added a custom validator which uses strings for `shape` and `expected_shape`. I believe all criteria are met. It would be great if someone else would check it out.
> 
> The branch:
> https://github.com/BAMWelDX/weldx/tree/42_shape_validation
> 
> Questions:
> 
> * is the `shape` a String or is it something else?
> * are there "[" in the strings - since we are operating with lists?

* Input of `_custom_shape_validator(shape, expected_shape):` will be List of Ints for `shape` and a List of Int/Strings for `expected_shape`
* the original yaml looks like this for shape `[4,5,2,1]` and the same for `expected_shape` (example: `[4,5,:,1,...]` so we cannot use addition `[ ]` as this would probably break the yaml parser

Some important notes regarding allowed syntax that passes the yaml parser:
* `:` and '*' break during parsing so we cannot use these
* `~` can be used instead of `:` but will be converted to `None` in the python list if it is a lone entry

Here is an example what we get from yaml 
```yaml
[1,3,(5),4~7,~,(~),n,(n),...]
```
to python list:
```python
[1, 3, '(5)', '4~7', None, '(~)', 'n', '(n)', '...']
```
Other than `~` -> `None` this seems straight-forward

**Comment by mark141** [comment]
The `_custom_shape_validator` now accepts List of Ints for `shape` and a List of Int/stings for `expected_shape`.
It will replace all `None` and all `~` found with `":"`. So both inputs can be used.

**Comment by CagtayFabry** [comment]
We should also allow optional dimensions appearing in the beginning of `expected_shape` and validate in reverse order in this case. So the following should be equally valid:
```python
val([1, 2], [1, 2, "..."])
val([1, 2], ["...", 1, 2])

val([1, 2], [1, 2, "(3)"])
val([2, 3], ["(1)", 2, 3])
```

I Have updated the tests with more cases, take a look @mark141

**Comment by mark141** [comment]
* [x] Added improved docstrings to the functions in validate_shapes.py.
* [x] Fixed error in validation of val([1, 2], [1, "(1\~3~5)"])
* [ ] .md file for Shape Validation Syntax in a new 'doc' folder to Project


Active branch:
https://github.com/BAMWelDX/weldx/tree/42_shape_validation_2

**Comment by CagtayFabry** [comment]
So regarding syntax the only missing "feature" seems to be allowing `(3)` or `(n)` before `...`:

https://github.com/BAMWelDX/weldx/blob/e5660ecb4587b994e8d078938225c0e6e9935d68/tests/test_asdf.py#L423

I think it might be useful but not urgent since we don't really have important use cases for `...` so far. So maybe add this later if we need to.
What do you think @vhirtham ?

can you look into how complex the changes would be to make this work @mark141 ?

**Comment by CagtayFabry** [comment]
> So regarding syntax the only missing "feature" seems to be allowing `(3)` or `(n)` before `...`:
> 
> https://github.com/BAMWelDX/weldx/blob/e5660ecb4587b994e8d078938225c0e6e9935d68/tests/test_asdf.py#L423
> 
> I think it might be useful but not urgent since we don't really have important use cases for `...` so far. So maybe add this later if we need to.
> What do you think @vhirtham ?
> 
> can you look into how complex the changes would be to make this work @mark141 ?

This syntax is now allowed on `dev_asdf`
