### ISSUE TITLE
sort string list output in asdf tree

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#423]
in some places we store lists of strings in asdf files, most for the CSM and related functions notably here:
https://github.com/BAMWelDX/weldx/blob/9ffdba4c3594fe9bd73f214005d2a6ab8314369d/weldx/asdf/tags/weldx/core/transformations/coordinate_system_hierarchy.py#L83-L92

The sorting of these list items seem to change randomly when (re)creating files.
For consistency and better diffs it would be nice to sort these kind of lists before writing them to asdf.

Need to check if the order might be relevant to the implementation but I guess not for most cases?

**Comment by vhirtham** [comment]
Do you have any general solution in mind. Otherwise, I would just sort the affected lists in the to_tree method using one of the methods showcased [here](https://stackoverflow.com/a/36156/6700329). Using `.sort` on a copy will probably be sufficient.

**Comment by CagtayFabry** [comment]
I guess just modifying `to_tree` with some kind of `.sort` is the easiest solution

**Comment by vhirtham** [comment]
Any other known issues apart from the CSM?

**Comment by CagtayFabry** [comment]
I haven't looked but maybe search for `List[str]` type hints or `array`s in yaml of type string for the elements
