### ISSUE TITLE
Add mypy to CI pipelines

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#427]
`mypy` is a tool that checks if the correct types are used (for example during a function call). It uses python type annotations and compares them against the actual type in use. 

Here is the [GitHub repo](https://github.com/python/mypy) and the [documentation](https://mypy.readthedocs.io/en/stable/). Since Guido van Rossum (somebody told me this guy knows a bit about python 😉) participates in the project, I guess it might be a good choice over other alternatives. I just tried it on our `core.py`. Here is the output:

~~~
weldx\core.py:298: error: Argument 3 to "_initialize_discrete" of "TimeSeries" has incompatible type "Optional[str]"; expected "str"  [arg-type]
weldx\core.py:326: error: "None" has no attribute "identical"  [attr-defined]
weldx\core.py:376: error: Argument 1 to "rename" of "DataArray" has incompatible type "Dict[str, str]"; expected "Union[Hashable, Mapping[Hashable, Hashable], None]"  [arg-type]
weldx\core.py:376: note: Following member(s) of "Dict[str, str]" have conflicts:
weldx\core.py:376: note:     __hash__: expected "Callable[[], int]", got "None"
weldx\core.py:436: error: Argument 1 to "xr_interp_like" has incompatible type "None"; expected "DataArray"  [arg-type]
weldx\core.py:438: error: Argument "method" to "xr_interp_like" has incompatible type "Optional[str]"; expected "str"  [arg-type]
weldx\core.py:468: error: "None" has no attribute "evaluate"  [attr-defined]
weldx\core.py:476: error: Argument 1 to "rename" of "DataArray" has incompatible type "Dict[str, str]"; expected "Union[Hashable, Mapping[Hashable, Hashable], None]"  [arg-type]
weldx\core.py:476: note: Following member(s) of "Dict[str, str]" have conflicts:
weldx\core.py:476: note:     __hash__: expected "Callable[[], int]", got "None"
weldx\core.py:618: error: Incompatible return value type (got "None", expected "Tuple[Any, ...]")  [return-value]
weldx\core.py:632: error: Incompatible return value type (got "None", expected "str")  [return-value]
~~~

We will certainly have to put a bit of work into fixing all issues in the package and tweaking the tool, but most of the stuff should be simply adjusting wrong type annotations due to interface changes, etc.

I think it will further improve the quality of our package. What do you think?

**Comment by CagtayFabry** [comment]
I am not sure how much effort is needed to update all the type hints, it is probably overkill for the whole package

imo it makes sense when other tools (such as numba) get involved or with c interfaces etc.

Maybe we could give it a try in a PR only for the `core` module and see how the changes might look like?

**Comment by vhirtham** [comment]
> I am not sure how much effort is needed to update all the type hints, it is probably overkill for the whole package
> 
> imo it makes sense when other tools (such as numba, dask) get involved or with c interfaces etc.
> 
> Maybe we could give it a try in a PR only for the `core` module and see how the changes might look like?

Since `core.py` is one of our larger files I am quite confident, that it wouldn't bet that much of an overkill. Also, the fixes seem to be pretty simple. Just correct the type hint (note that no type hint is no error). We can try it in a PR and see how it goes
