### ISSUE TITLE
`Time.__eq__` return type

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#447]
The current return type of `Time.__eq__` is `Union[bool, List[bool]]`. The list is returned when the internal data is an array. I am not sure if this is a good idea. If I use `==`, I expect either `True` or `False` as return value and not a list of results that I need to evaluate with `all`. I also do not see a practical use-case except some debugging where I need a list of bools instead of a single bool. So my suggestion would be to use only `bool` as return type.

To further support my pointy here is what mypy thinks:

~~~
weldx\time.py: note: In member "__eq__" of class "Time":
weldx\time.py:273:5: error: Return type "Union[bool, List[bool]]" of "__eq__" incompatible with return type "bool" in supertype "object"  [override]
        def __eq__(self, other: Union[types_time_like, Time]) -> Union[bool, List[bool]]:
        ^
~~~

I silenced the warning for now on the mypy branch, but we should remove the `# type: ignore` if we change the interface.

**Comment by CagtayFabry** [comment]
> The current return type of `Time.__eq__` is `Union[bool, List[bool]]`. The list is returned when the internal data is an array. I am not sure if this is a good idea. **If I use `==`, I expect either `True` or `False` as return value and not a list of results** that I need to evaluate with `all`. I also do not see a practical use-case except some debugging where I need a list of bools instead of a single bool. **So my suggestion would be to use only `bool` as return type.**

I disagree for the `Time` class since it is basically a wrapper around `pandas` Index types or pint/xarray objects which I would describe as 'array-like'. I would stick to numpy convention of doing element-wise comparison for `==` and using `.equals` or simply `np.all` if wanted.

**Comment by vhirtham** [comment]
> > The current return type of `Time.__eq__` is `Union[bool, List[bool]]`. The list is returned when the internal data is an array. I am not sure if this is a good idea. **If I use `==`, I expect either `True` or `False` as return value and not a list of results** that I need to evaluate with `all`. I also do not see a practical use-case except some debugging where I need a list of bools instead of a single bool. **So my suggestion would be to use only `bool` as return type.**
> 
> I disagree for the `Time` class since it is basically a wrapper around `pandas` Index types or pint/xarray objects which I would describe as 'array-like'. I would stick to numpy convention of doing element-wise comparison for `==` and using `.equals` or simply `np.all` if wanted.

When do we ever need the element-wise comparison results? Maybe numpy has a good reason to break with the basic expected behavior of the `==` operator, but what do we need that for? I find this behavior already annoying on numpy types and it is certainly not a recommended one (see mypy warning)

**Comment by vhirtham** [comment]
Here is a snippet of the [Python documentation](https://docs.python.org/3/reference/datamodel.html) regarding this topic:

> A rich comparison method may return the singleton NotImplemented if it does not implement the operation for a given pair of arguments. **By convention, False and True are returned for a successful comparison.** However, these methods can return any value, so if the comparison operator is used in a Boolean context (e.g., in the condition of an if statement), Python will call bool() on the value to determine if the result is true or false.

**Comment by marscher** [comment]
Actually one would need to define (and establish, much worse) a new interface like `__array_equal__` to prevent breaking existing an interface. I really do not understand why pandas broke this in the first place. Perhaps they did it because it's just convenience. The problem with this kind of interface breakage is, that all users of the class need to treat the case of two (very differently behaving) return type for a super basic operation. If the using code does not treat the new special case, things will break horrible and at unexpected spots. This principle does not only apply to Python but just any programming language (please correct me if I'm wrong).

Since the `__eq__` operation is defined by the standard data model of Python, I strongly advice not to break it (again). I guess introducing this change in Pandas also gave rise to a discussion about basic principles.

**Comment by marscher** [comment]
For a strict array-like type it makes sense to always return an array. Our special case of wrapping both single dates and series we should downcast to plain bool.

**Comment by CagtayFabry** [comment]
> > > The current return type of `Time.__eq__` is `Union[bool, List[bool]]`. The list is returned when the internal data is an array. I am not sure if this is a good idea. **If I use `==`, I expect either `True` or `False` as return value and not a list of results** that I need to evaluate with `all`. I also do not see a practical use-case except some debugging where I need a list of bools instead of a single bool. **So my suggestion would be to use only `bool` as return type.**
> > 
> > 
> > I disagree for the `Time` class since it is basically a wrapper around `pandas` Index types or pint/xarray objects which I would describe as 'array-like'. I would stick to numpy convention of doing element-wise comparison for `==` and using `.equals` or simply `np.all` if wanted.
> 
> **When do we ever need the element-wise comparison results?** Maybe numpy has a good reason to break with the basic expected behavior of the `==` operator, but what do we need that for? I find this behavior already annoying on numpy types and it is certainly not a recommended one (see mypy warning)

I would use it for indexing/masking operations

certainly we need an element-wise comparison, so what would be call that function?

**Comment by vhirtham** [comment]
> > > > The current return type of `Time.__eq__` is `Union[bool, List[bool]]`. The list is returned when the internal data is an array. I am not sure if this is a good idea. **If I use `==`, I expect either `True` or `False` as return value and not a list of results** that I need to evaluate with `all`. I also do not see a practical use-case except some debugging where I need a list of bools instead of a single bool. **So my suggestion would be to use only `bool` as return type.**
> > > 
> > > 
> > > I disagree for the `Time` class since it is basically a wrapper around `pandas` Index types or pint/xarray objects which I would describe as 'array-like'. I would stick to numpy convention of doing element-wise comparison for `==` and using `.equals` or simply `np.all` if wanted.
> > 
> > 
> > **When do we ever need the element-wise comparison results?** Maybe numpy has a good reason to break with the basic expected behavior of the `==` operator, but what do we need that for? I find this behavior already annoying on numpy types and it is certainly not a recommended one (see mypy warning)
> 
> I would use it for indexing/masking operations
> 
> certainly we need an element-wise comparison, so what would be call that function?

In such a case one can still do `t1.as_pandas() == t2.as_pandas()` or we intruduce `equals_element_wise` or something similar.

**Comment by CagtayFabry** [comment]
I talked about it again with @vhirtham and decided to keep the current (array like implementation) for now.
This is mostly to keep a consistent behaviour with the existing `numpy`, `pint`, `pandas` and `xarray` interfaces we already use.

We can reevaluate later when we have more code use-cases of the `Time` class
