### ISSUE TITLE
[doc/changelog] link objects to api doc 

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#453]

**Comment by CagtayFabry** [comment]
sounds great, is there a way we could make this work?

**Comment by marscher** [comment]
I gave it a shot by setting directive "currentmodule" to make sphinx find the objects during inclusion of the changelog. Without success yet.

**Comment by marscher** [comment]
Lets see: https://github.com/CrossNox/m2r2/issues/37

**Comment by marscher** [comment]
@CagtayFabry suggested to convert the changelog to RST and store it directly in the documentation, this would make it easier to achieve the linking of objects. We also need to consider what happens with deleted objects (unlink them manually, silent failure, etc.)
