### ISSUE TITLE
xarray.Variable deserialization casts NDArrayType (asdf) to np.ndarray

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#454]
As a consequence, memory mapping of stored arrays does not work, e.g. copy_arrays flag has no effect.

**Comment by vhirtham** [comment]
Just for further clarification, this is the line we are talking about:

https://github.com/BAMWelDX/weldx/blob/670b45f6e6a80324fb7ca063d91c44cebd376b3f/weldx/asdf/tags/weldx/core/common_types.py#L137
