### ISSUE TITLE
differentiate and custom tag xarray types

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#47]
Depending on the contents / layout of different xarray objects we might want to consider implementing different ASDF tags.

Example use case:
xarray objects with an appropriate time dimension could be tagged as `timeseries` or similar. This could lead to simpler and more epxlicit asdf schema definitions ($ref transformation, instead of $ref DataArray + validator)

Implementation ideas:
- we could subclass xarray datatypes for our own datatypes
  - not sure if this is the best approach, see http://xarray.pydata.org/en/stable/internals.html#extending-xarray
  - might get complicated when mixing DataArray/Dataset types
- we could also add a special attribute to xarray objects (like `_wx_tag`) that can be used to customize the tag in to/from_tree methods

**Comment by CagtayFabry** [comment]
not sure if this is worth pursuing any longer

**Comment by vhirtham** [comment]
I think we can keep this approach in mind if something comes up where it fits, but currently, I do not see a particular use case. Close if you like.
