### ISSUE TITLE
`TimeSeries` todos

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#471]
The `TimeSeries` basically supports absolute times since PR #440.  But this support is not really tested and there are probably still some execution paths that might fail (see todo in `_initialize_discrete`). Additionally, the reference time should be stored inside the internal xarray data structure as suggested by @CagtayFabry in this PR #468.

List of todos:
- Check code for missing consideration of absolute times
- Add missing test cases for absolute times
- Store reference time directly inside of internal xarray structure 

I am not sure about this, but we might also consider moving the `TimeSeries` to the time package

**Comment by marscher** [comment]
makes total sense to store time related classes next to each other.
