### ISSUE TITLE
conda build errors

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#474]
In current PRs there are a few errors (and lots of warnings) popping up in the conda build CI pytest run ([example](https://github.com/BAMWelDX/weldx/pull/473/checks?check_run_id=3328082912))

The errors do not appear on the pypi build run

### errors
- all the warnings seem to be related to `WeldxFile`.
I have no idea why or when the http calls are created. Maybe the error will be clearer after getting rid of the `http://` prefix in #467 .
(seems to work: https://github.com/BAMWelDX/weldx/runs/3328656041?check_suite_focus=true)
- What is strange to me is the sole `RepresenterError` for `xarray.DataArray` in `TestWeldXFile.test_compression`. Usually the type should be picked up here... (it works in other tests)

### warnings
- every test marked with `slow` throws a warning because the pytest marker is not recognized.
I guess this has to do with the `setup.cfg` not being part of the distribution, hence the pytest config is not applied.

### others
maybe unrelated but [these](https://github.com/BAMWelDX/weldx/pull/467/checks?check_run_id=3328463803#step:9:111) [two](https://github.com/BAMWelDX/weldx/pull/467/checks?check_run_id=3328463803#step:9:111) errors popping up with `WeldxFile.test_custom_schema` also don't make a lot of sense to me
since we currently use `asdf.info` (which at least seems to do some kind of type resolving under the hood) to create the console output that is a little hard to debug, can we revert that to simply print the yaml string in the console again @marscher ?

**Comment by CagtayFabry** [comment]
This might be related to updated dependencies in the `k3d` conda build, testing now (woulöd fit the timeframe of the error appearing)

**Comment by CagtayFabry** [comment]
#473 seems to have solved the errors for now

**Comment by CagtayFabry** [comment]
I think this has been solved?
the only thing still open are the pytest marker warnings but I'm not sure we can do mcuh about those (also they don't really matter for the build runs)

**Comment by marscher** [comment]
I think these warnings arise from the `conftest.py` not being shipped to the testing (run) folder.

**Comment by CagtayFabry** [comment]
yes true for the warning, but I believe this is fine for now :)
