### ISSUE TITLE
Typo CI was removed

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#475]
Typo CI has been removed by its owner ([see here](https://mikerogers.io/2021/05/23/saying-goodbye-to-typo-ci)). I am currently looking for an alternative.

**Comment by CagtayFabry** [comment]
good to know, thanks
too bad non of the (apparently existing) GitHub actions alternatives are listed

**Comment by vhirtham** [comment]
> too bad non of the (apparently existing) GitHub actions alternatives are listed

Yes, it's a pity, but one finds quite a bit if you search for "spellchecker" or "typo". We just have to evaluate which one fits our needs best. The thing that I didn't like about typo CI was that it failed silently. It was easy to miss some typos. Ideally, the new tool explicitly marks the pull request as failed if a typo is found but it should not block and should not run on master (so we do not get a red "x" for having a typo on the master branch)

**Comment by CagtayFabry** [comment]
I think failing CI/PR for a typo is a bit strict, I actually like the annotations (though a concise report would be nice)

**Comment by vhirtham** [comment]
It's just to get a visual hint, that there actually are some typos. Travis had a nice feature, where you could mark certain runs as "allowed to fail". If those runs actually failed, the whole build was still counted as a success. Such a feature would be nice for GH too.

**Comment by marscher** [comment]
https://github.com/marketplace/actions/check-spelling This seems worth a try, it offers a more programming friendly way of checking, e.g. CamelCasing will be recognized.
The other real GH action alternative is this one https://github.com/marketplace/actions/github-spellcheck-action
It uses pyspelling as backend.
