### ISSUE TITLE
sympy string notation for simple math operations

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#48]
discuss using sympy-compatible string notation of basic math operations and formulas and implement draft asdf schema

**Comment by vhirtham** [comment]
We implemented a first version in commit 77997f1113aa530ce31fb2827f2525238b4583a1 of the `measurement_asdf` branch.

Using SymPy makes things easy. Every formula can be converted into a string using the `__str__` function. It can be converted back to SymPy using the `sympify` function. One should always pass `evaluate=False` as an additional parameter to avoid that SymPy optimizes the formula without explicit instruction to do so. 

Additionally, the function `lambdify` can be used to turn the mathematical expression into a Python function with NumPy support.

We wrote a small class that stores a mathematical formula using SymPy and that provides the option to define fixed values/quantities for each symbol of the expression. It can already be written to and read from an asdf file. 

Additionally, the class provides an `evaluate` function that calculates the results of the expression. Each symbol that does not already have a value assigned to it in the class needs to be passed as a keyword argument. For example, if we had the expression`"a*x+b"` and `a` and `b` are already have fixed values stored inside the class, then one might use `f.evaluate(x=3)` to get the function value at `x=3`. One important aspect is that the internally stored values and the passed values can be any type that is compatible with NumPy (`xarray.DataArray`, Pint Quantities, etc.).

Internally this works by simply combining the stored values and the parameters to the `evaluate` function in a common dictionary and passing this as keyword arguments to the "lambdified" expression.

**Comment by CagtayFabry** [comment]
Since [`sympify`](https://docs.sympy.org/latest/modules/core.html) uses `eval` it might be good to add a simple string preprocessor upon reading from the file.

https://stackoverflow.com/questions/16718644/how-safe-is-sympys-sympifystring-evalf
https://stackoverflow.com/questions/3513292/python-make-eval-safe
