### ISSUE TITLE
filter action runs

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#481]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by vhirtham** [comment]
So if I get this right, we can simply skip for example our `pytest` runners if we filter the `weldx` directory and nothing changed in it?

**Comment by CagtayFabry** [comment]
yes, I just stumbled upon that and wanted to keep a reminder

a few ideas:
- don't run pytest for changes only to `CHANGELOG.md`, `doc/**` etc.
- only run pytest/build for changes to the python package and tutorials
- don't run linters if no code changes

we should always run everything on master and tags though I guess
