### ISSUE TITLE
asdf implementation of scipy rotation object

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#49]
implement a basic `rotation` schema based on the [`scipy.spatial.transform.Rotation`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html)

The idea is to preserve the original input style (`from_euler`, `from_quat` etc.) to keep a verbose YAML representation in the output file
Since this information is lost after initialization on the scipy `Rotation` class maybe one approach is to subclass `Rotation` and overwrite the `from_*` constructors to add an additional property `_wx_meta` storing relevant metadata

```python
class Rotation():
    @classmethod
    def from_euler(seq, angles, degrees=False):
        meta = {"constructor": ScipyRotation.from_euler, "seq": seq, "degrees": degrees}
        rot = ScipyRotation.from_euler(seq="x",angles=20,degrees=True)
        rot._wx_meta = meta
        return rot
```

**Comment by vhirtham** [comment]
Do you have a specific use-case in mind since I can't see much of a benefit here? A human reader might find Euler angles a little bit easier to understand but in the end, the information stays the same, regardless of the chosen representation. You can always calculate one representation from the other.

**Comment by CagtayFabry** [comment]
> 
> 
> Do you have a specific use-case in mind since I can't see much of a benefit here? A human reader might find Euler angles a little bit easier to understand but in the end, the information stays the same, regardless of the chosen representation. You can always calculate one representation from the other.

Exactly, it is also easier to verify the information directly form the asdf header.
ASDF has simliar implementations https://asdf-standard.readthedocs.io/en/1.5.0/generated/stsci.edu/asdf/transform/rotate_sequence_3d-1.0.0.html
