### ISSUE TITLE
WeldxFile copy has ambigious interface

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#493]
Currently the we derive the class from UserDict to give a dictionary like usage pattern. The copy method just returns a copy of the internally mapped dictionary, but not the file itself. I think a user of this class would expect the latter. So we should discuss some cases here.

1. Copy the whole file (copy data and file)
2. Copy only the internal data (leave things as they are)
3. Break the interface of copy by passing an optional file argument

For 1. we have the additional case of an existing filename. So we can automatically put a prefix like "copy of $fn" to it or raise an Exception.

Option 2 has the previously discussed downside of having unexpected behavior.

Option 3 sounds most reasonable to me at the moment.

**Comment by CagtayFabry** [comment]
I also think 3 sounds good, better not to have an interface than some unexpected or hard to explain behavior
