### ISSUE TITLE
pip installation requires compiler (due to bottleneck dependency)

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#524]
The bottleneck library does not provide binaries, so users would have to install a full build environment. This should be noted in the installation docs, so users are warned and use conda as prefered method.

**Comment by CagtayFabry** [comment]
I think `asdf` also doesn't provide binaries (wheels?)

**Comment by marscher** [comment]
asdf is a pure Python project, so there is nothing to compile.

**Comment by CagtayFabry** [comment]
ahhh I see 😁
