### ISSUE TITLE
documentation fixes

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#526]
some minor points regarding the documentation

- the `Q_` docstring seems to have some errors in the examples formatting: https://weldx.readthedocs.io/en/latest/_autosummary/weldx.Q_.html
- `Time` is missing at the user API section (should be next to `Q_` I guess)
- can we get the objects listed in the `constants` module? https://weldx.readthedocs.io/en/latest/_autosummary/weldx.constants.html (not sure how this works, do we add docstrings?)
- move `GEOMETRY` section to the end of the user API documentation (imo)

**Comment by marscher** [comment]
sphinx 4.2.0 should respect the `__all__` variable. If things are listed there, they will be documented, even if they are just imports. This bug was open since 2015 and should make our life's much easier.

**Comment by marscher** [comment]
Ah this has not yet been released. Its on hold for having a config options. https://github.com/sphinx-doc/sphinx/pull/9455

**Comment by CagtayFabry** [comment]
too bad, let's hope for speedy implementation :)
