### ISSUE TITLE
default tag version

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#531]
with `0.5.0` and the switch to the new ASDF extension API we also get a 'fresh start' with the version numbering

I would prefer to reserve the `1.0.0` version for schema files for the initial (final) `1.0.0` release of weldx
But since there are now use cases based on the format we should also keep compatibility in mind from `0.6.0` forward.

So I am thinking, maybe we should reset the schema versions to `0.1.0` and apply all the versioning mechanisms of asdf going forward. We don't have to keep backwards compatibility code in the codebase for too long imo but should avoid breaking files between releases (like we are doing now with the old tag format)

~~I might remember trying to set a `0.1.0` version somewhere before and running into some kind of issue but not sure so I will try it again just to see if that is viable~~
everything seems to work fine with `0.1.0` #535

please offer your opinions @vhirtham @marscher @AndreasPittner

**Comment by CagtayFabry** [comment]
I have implemented the changes here #535, everything seems to work 🎉

**Comment by vhirtham** [comment]
I think the schema version number only gets relevant if we finally release WelDX `1.0.0`. So setting it back to `0.1.0` is fine by me. Has the additional benefit, that we can increase it freely if we want to test our versioning procedures later.

**Comment by CagtayFabry** [comment]
> I think the schema version number only gets relevant if we finally release WelDX `1.0.0`. So setting it back to `0.1.0` is fine by me. Has the additional benefit, that we can increase it freely if we want to test our versioning procedures later.

yes we should definitely do some test runs with versioning

**Comment by marscher** [comment]
I've just noticed that you reimported the legacy tags to support reading "old" files again. As users probably never has to work with tag versions themself it is purely cosmetic at this point to reset the versions. But breaking compatibility with old files (you might argue that there are no files yet) is bad. I already run into trouble with asdf-2.8 new tag layout on old files and I guess artificially down-grading tag version numbers will not increase backward compatibility.

I'd just use semantic versioning for the tags, no matter whats' the current stage of the project. This way we could learn how to do it properly and as I said before, the version does not really affect the user.

**Comment by CagtayFabry** [comment]
> I'd just use semantic versioning for the tags, no matter whats' the current stage of the project. This way we could learn how to do it properly and as I said before, the version does not really affect the user.

yes that is exactly the idea from now on, just use semantic versioning for schemas etc.

> I've just noticed that you reimported the legacy tags to support reading "old" files again. As users probably never has to work with tag versions themself it is purely cosmetic at this point to reset the versions. But breaking compatibility with old files (you might argue that there are no files yet) is bad. I already run into trouble with asdf-2.8 new tag layout on old files and I guess artificially down-grading tag version numbers will not increase backward compatibility.
> 

that is why I wanted to do this now with the big asdf 2.8 refactor

Since the *old* and *new* schema files use a completely different naming scheme there is no real versioning conflict going 'down' to 0.1.0 now.
basically we are deprecating the `tag:weldx.bam.de` namespace completely (but still support it via the legacy files)
the new `asdf://weldx.bam.de` tag namespace is completely unrelated to the old schemas now (although obviously the file layout etc are still the same, but we could also change that)
