### ISSUE TITLE
Pydocstyle setup broken

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#543]
While working on the `geometry` package I realized that pydocstyle does not report issues anymore. It passes no matter which documentation crime I commit. This seems to be related to the recent pre-commit PRs since removing the '"' here fixes the problem partially:

**`setup.cfg`** 
~~~ python
[pydocstyle]
# convention numpy is currently equivalent to ignoring 'D107', 'D203', 'D212', 'D213', 'D402', 'D413'
convention = numpy
# match options need to be in "" for pre-commit
match = "(?!__)(?!_version)(?!conftest).*\.py"
match_dir = "[^\.][^\docs][^\tags].*"
~~~

But the problem remains for example for the files of the `transformations` package. My first thought was that subfolders might be ignored generally, but it works normally for `util`. So it must get skipped for some other reason I haven't figured out yet.

**Comment by CagtayFabry** [comment]
hmm that's too bad, we can comment out pydocstyle in pre-commit and remove the `"` in `setup.cfg`, that should return it to the old settings

however not sure why some submodules might not get picked up

**Comment by CagtayFabry** [comment]
I wonder if those regex pieces ever did what I think they would...
should work now though, I have excluded the tests folder for now
