### ISSUE TITLE
readthedocs: git repo does not contain latest tag information

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#549]
As we derive the version number via setuptools_scm it is crucial to have all the git tags during the build. The version number of the latest build is something "0.1.dev50..." not "0.4.1+devX". I have not found any git related options in the RTD admin tab so far. I think the working copy and the doc build directory are kept to speed up building.
Eventually we need to report this upstream.

**Comment by CagtayFabry** [comment]
i think this might also happen if the fetch depth of the git repo is not sufficient (if you don't fetch tags you cannot determine the latest (and next) version)

look at the changes in the GH actions [here](7469702bdc77e0669c995b69007098ef1aaa32e3) I made for this reason
before, the weldx version tag could not be determined correctly ([weldx-0.1.dev1+gd3d1289](https://github.com/BAMWelDX/weldx/runs/3587586361#step:4:221))
with all tag info it gets resolved as it would locally ([weldx-0.4.2.dev52+g288a28b](https://github.com/BAMWelDX/weldx/runs/3588123972))

**Comment by marscher** [comment]
Yes, this is the cause. So we need to unshallow the git working copy on RTD.

**Comment by CagtayFabry** [comment]
we could take a look into how other projects deal with this, should be pretty common I guess

**Comment by marscher** [comment]
https://github.com/readthedocs/readthedocs.org/issues/5989
