### ISSUE TITLE
weldxfile: consider removing asdf metadata from user dictionary like operations.

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#557]
During writing examples (doctests) for WeldxFile, I noticed that it would be bad, if users are able to delete basic asdf meta data like history, software versions etc.
So I'd suggest to remove these data from the users view, restricting it to the data he or she has actually wanted to be in the file (dictionary). Of course the data is still there and will be written as such, but just became immutable. For `history` we already have an interface. So we'd need to another getter for software.

**Comment by CagtayFabry** [comment]
great idea, those parts should not be open to the user 👍

**Comment by CagtayFabry** [comment]
since I just saw it in the other PR:
would it be enough to just `pop` the keys that we don't want the user to fiddle with from the mapping here before applying the update?
https://github.com/BAMWelDX/weldx/blob/ebc43d769715fb08a59ec5463f9b701083355ef2/weldx/asdf/file.py#L554-L555

**Comment by marscher** [comment]
> 
> 
> since I just saw it in the other PR: would it be enough to just `pop` the keys that we don't want the user to fiddle with from the mapping here before applying the update?
> 
> https://github.com/BAMWelDX/weldx/blob/ebc43d769715fb08a59ec5463f9b701083355ef2/weldx/asdf/file.py#L554-L555

That is a rude workaround I came up with (actually just to compress the output for the user). But we should not remove these keys permanently as they contain important information, which would be lost otherwise.

**Comment by CagtayFabry** [comment]
> > since I just saw it in the other PR: would it be enough to just `pop` the keys that we don't want the user to fiddle with from the mapping here before applying the update?
> > https://github.com/BAMWelDX/weldx/blob/ebc43d769715fb08a59ec5463f9b701083355ef2/weldx/asdf/file.py#L554-L555
> 
> That is a rude workaround I came up with (actually just to compress the output for the user). But we should not remove these keys permanently as they contain important information, which would be lost otherwise.

maybe I misunderstand the function, my idea was this

```python 
def update(self, mapping: Union[Mapping, Iterable] = (), **kwargs):
        mapping.pop("history")
        super().update(mapping, **kwargs)
```
the `mapping` here is what the user wants to update, right? (And where he or she might actually pass those keys.)
I don't want to pop anything form the file tree itself
