### ISSUE TITLE
`WeldxFile` content printer for pure Python

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#558]
For jupyter notebooks, we can visualize the content of a WeldxFile rather easily in a non-verbose way with `show_asdf_header`.
In pure python however, I can only print the unwieldy asdf YAML header or start to write some custom code to navigate manually through the tree (unless I missed something in the tutorial). It shouldn't be too hard to write a function (or expand `show_asdf_header`) that traverses the tree recursively until it finds an object that is not a container and prints its type.
So an output like this would be nice (comments are just for understanding the principle and won't be in the true output):

~~~
# Object items
- coordinate_systems: <CoordinateSystemManager>
- measurements: <MeasurementChain> 
# List and set items
- data:
    - <SpatialData>
    - <SpatialData>
    - <SpatialData>
# dictionary items
- wxmeta:
    - welder: <str>
    - timestamps:
        - start: <Time>
        - end: <Time>  
    - error:
        - failurecode: <int>
        - message: <str>
~~~

This way I know exactly how to navigate through a tree to get the item I want.

For lists we might think of a different solution though, like just printing the different types in it and its length

What do you think @marscher @CagtayFabry

**Comment by CagtayFabry** [comment]
I am not sure I exactly understand what the output would look like, would you omit the class contents for the class name?
can you post a full asdf header that would create your example?

it looks to me like something similar can be done with [asdf.info](https://asdf.readthedocs.io/en/stable/api/asdf.info.html?highlight=info#asdf.info)

if you are looking for a specific object in the tree, [asdf.search](https://asdf.readthedocs.io/en/latest/asdf/user_api.html#module-asdf.search) might also come in handy

**Comment by vhirtham** [comment]
So `asdf.info` did pretty much what I wanted. See #576
