### ISSUE TITLE
base welding file schema

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#60]
Implement base file layout using ASDF `custom_schema`

# elements:
- measurements
- equipment
- coordinate system manager
- geometry / groove
- reference timestamp
- experimental metadata

**Comment by vhirtham** [comment]
You forgot the measurement data 😄

**Comment by CagtayFabry** [comment]
> You forgot the measurement data 😄

fixed, I meant whatever is the top level measurements container
