### ISSUE TITLE
Custom schema printing tool

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#606]
The idea is to have a tool that can print the content of a custom schema used for file validation (for example `single_pass_weld.yaml`) in a way that is easy to read. The purpose is mainly to give a user of the python API who wants to create a new WelDX file a quick overview of the requirements and optional fields to pass the schema validation without the need to actually take a look into the schema. 

Ideally, the output would be similar to `asdf.info` just for schemas, not for files. This would also give the python user the information about which types he has to put into the tree which is probably more useful to him than a tag (some tags are not named like the related python objects --- 👀 @ U ...CSM). The tool should also differ between required and optional fields.

Another possible implementation variant suggested by @CagtayFabry would be to generate an expandable HTML object like the `view_tree` method does when working with jupyter notebooks.

**Comment by CagtayFabry** [comment]
here is a snippet that works for schemas using the JupyterLab JSON tool
```python
import asdf
from boltons.iterutils import remap
from IPython.display import JSON

from weldx.asdf.util import get_schema_path

schema = get_schema_path("single_pass_weld-0.1.0")
contents = schema.read_text()
header = asdf.yamlutil.load_tree(contents)

remapped = header["properties"]

#print("original dict")
#display(JSON(remapped, expanded=False, root=schema.name))

def add_tag_to_key(path, key, value):
    if not isinstance(value, dict):
        return key, value

    if "tag" in value:
        converter = get_converter_for_tag(value["tag"])
        if converter:
            tag_str = converter.types[0]
        else:
            tag_str = value["tag"].split("asdf://weldx.bam.de/weldx/tags/")[-1]
        key = f"{key} ({tag_str})"
    elif "$ref" in value:
        tag_str = value["$ref"].split("asdf://weldx.bam.de/weldx/schemas/")[-1]
        key = f"{key} (${tag_str})"
    elif value.get("type") == "object":
        key = f"{key} (object)"
    elif value.get("type") == "array":
        key = f"{key} (array)"
    elif value.get("type") == "string":
        key = f"{key} (string)"
    elif value.get("type") == "number":
        key = f"{key} (number)"
    return key, value


def convert_wx_shape(path, key, value):
    if isinstance(value, dict) and ("wx_shape" in value):
        if isinstance(value["wx_shape"], list):
            value = value.copy()
            value["wx_shape"] = f"[{','.join((str(n) for n in value['wx_shape']))}]"
    return key, value


drop_meta = lambda p, k, v: k not in {
    "examples",
    "description",
    "required",
    "tag",
    "$ref",
    "type",
}


def drop_properties(path, key, value):
    if not isinstance(value, dict):
        return key, value
    if "properties" in value:
        value = value["properties"]
    return key, value


remapped = remap(remapped, visit=convert_wx_shape)
remapped = remap(remapped, visit=add_tag_to_key)
remapped = remap(remapped, visit=drop_meta)
remapped = remap(remapped, visit=drop_properties)

print("reworked dict")
display(JSON(remapped, expanded=False, root=schema.name))
```

as you can see, it is rather easy to restructure the whole dict with `remap` to shape the output.
Some things are a little more involved and the details (like how to display class names) probably need some careful fine tuning but in principle it's all there :)

example output:

![image](https://user-images.githubusercontent.com/43667554/138236692-2c9b56e0-e97d-46ce-a222-ca4e9fec9526.png)
