### ISSUE TITLE
new release or patched pypi release

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#624]
As pint-0.18 broke weldx-0.5.0 we have to decide what to do about the borken pypi 0.5.0 release. On conda-forge we just released an updated build of 0.5.0, but this aint possible for PyPI. We have to choose between the following choices:

1. quick release 0.5.1
2. upload a patched source archive with a different format and delete the old one

I think the first option is cleaner. I have performed option 2. in the past and it works. I just do not like that the tagged version from git does not match the source archive in this case. But that may be a neglect able detail.

**Comment by CagtayFabry** [comment]
we are basically ready for `0.5.1` pending #621 and #622, my plan was to release in the next days

**Comment by marscher** [comment]
I see, there were no issues assigned to the 0.5.1 milestone. I think we could postpone these PRs for 0.5.2 as they add new features, right? The pypi issue is a blocker. Nothing relying on units does work (which is essentially everything).

**Comment by CagtayFabry** [comment]
> I see, there were no issues assigned to the 0.5.1 milestone. I think we could postpone these PRs for 0.5.2 as they add new features, right? The pypi issue is a blocker. Nothing relying on units does work (which is essentially everything).

it works with the master or pint 0.17
