### ISSUE TITLE
weldxfile: catch ASDFWarnings for error handling

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#638]
Lately I stumbled again into an issue we already had. K3D depends on jupyterlab in its project requirements, but it does not in the current conda-forge release. This downstream issue prevents the loading of our ASDF extension. Unfortunately ASDF decided to catch this exception and just emit a warning in this case, leaving weldx ASDF extension completely broken. A warning will just print something more or less meaningful to stderr and the program just continues.

I suggest that we catch this warning in the WeldxFile class and turn it into an Exception pointing towards the issue.

**Comment by CagtayFabry** [comment]
yes for our usecases it probably makes more sense to raise an error here 👍
