### ISSUE TITLE
Generated dev version number is lower than released

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#657]
```
AsdfWarning: File 'test.wx' was created with extension URI 'asdf://weldx.bam.de/weldx/extensions/weldx-0.1.0' (from package weldx==0.5.2), but older package (weldx==0.5.2.dev9+g23ad669.d20211116) is installed.
```

So I guess the version generating code should at least increase the micro patch level, before adding the "devX" tag.
Eventually this is just a very minor detail, and we could suppress this warning. Or it can be tricky, if ASDF does some logic depending on this version checking.
Actually I would have thought that the dev version from this example should be considered higher, e.g.:

```
from distutils.version import LooseVersion as Version

assert Version("0.5.2") < Version("0.5.2.dev9+g23ad669.d20211116")
```
holds true. So it could be an upstream issue.

**Comment by CagtayFabry** [comment]
where did this pop up?
the current master reports version `weldx-0.5.3.dev3+g9a54ff7` when installed locally via pip, see [this action run](https://github.com/BAMWelDX/weldx/runs/4303208527?check_suite_focus=true#step:5:262)

**Comment by marscher** [comment]
having a pip installed version 0.5.2 inside a container, and modified the file with a git version. Eventually my git working copy lacks the latest tag information.

**Comment by CagtayFabry** [comment]
ah I see, hopefully a `git fetch --all` and `python setup.py --version` should fix this

**Comment by marscher** [comment]
It was the missing tag. Sorry for the noise :)
