### ISSUE TITLE
Not all valid TimeSeries objects can be serialized

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#671]
I am currently lacking the time to create a minimal reproducible example, but it seems like absolute times can not be serialized (correctly) with the current schema definition. You can see the problem in the file `CSM_Multi_Pass_example_old` in my scratch directory on the jupyter server. Just go to the cell that defines the function `get_bead_data` and change the lines

~~~ python
        curr_dat = w["UI"].U_HKS1
        curr = TimeSeries(Q_(curr_dat.data, "A"), Time(curr_dat.time).as_timedelta())

        volt_dat = w["UI"].I_HKS1
        volt = TimeSeries(Q_(volt_dat.data, "V"), Time(volt_dat.time).as_timedelta())
~~~

to 

~~~ python
        curr_dat = w["UI"].U_HKS1
        curr = TimeSeries(Q_(curr_dat.data, "A"), curr_dat.time)

        volt_dat = w["UI"].I_HKS1
        volt = TimeSeries(Q_(volt_dat.data, "V"), volt_dat.time)
~~~

and run everything again from this cell on.

You will get a validation error during the serialization.

**Comment by CagtayFabry** [comment]
I guess it is the same error as this snippet:
```python
import pandas as pd

from weldx import TimeSeries, Q_, Time, WeldxFile

data = Q_([1,2,3,4], "m")
t = pd.date_range(start="2020-01-01",freq="1D",periods=4)
ts = TimeSeries(data, t)

WeldxFile(tree={"ts":ts}, mode="rw")
```
