### ISSUE TITLE
versions 0.5.* are missing on PyPI/Conda-Forge

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#674]

**Comment by marscher** [comment]
I got confused by the fact that Python-3.10 is pinned :+1:

**Comment by marscher** [comment]
What was the reason for that again?

**Comment by CagtayFabry** [comment]
> What was the reason for that again?

`bottleneck` doesn't build on 3.10
Should we 'patch' the old conda releases to exclude 3.10? I a also noticed that an old weldx version get's installed in 3.10 environments

**Comment by marscher** [comment]
"Patching" releases on conda-forge is easy, as we would just update the meta.yaml, change the dependencies, and increase the build number. On PyPI it is recommended to upload a new release (haha).

**Comment by marscher** [comment]
Seems like bottleneck isn't really maintained any more (truck index of 1). https://github.com/pydata/bottleneck/issues/388

**Comment by CagtayFabry** [comment]
yes I saw that, let's hope that PR does get through somehow eventually
