### ISSUE TITLE
schemas for images/videos

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#686]
So far we don't have a schema representation of image or video data/files. Both images & videos share some similarities on how we might implement them so I will group them in this issue for now.

I guess the most common use cases would be

1.  adding an image/video as an external file (blob storage or external reference)
2.  adding an image/video as a raw data matrix (without compression)

To implement the first use-case we should probably add a `MIME type` field to the `file` schema to make thing easier to handle.
The second use-case is mostly suited for raw recordings, if available to input into image processing/ML applications.

Images as `file` should be straight forward, for raw data I suggest defining a suitable array format with coordinates such as `row/col` or similar.

Videos should also be easy but we should think about how to handle/read the associated timeline of the video into our data structures. A Video could then be a `file` with an additional `time` attribute.
For raw data, I guess it would make sense to have the video be a series of images with timestamps.

For both raw data we should look into which formats we might want to start with, I suggest at least `grey-scale` and `RGB` should be supported (maybe `HSL`?)

**Comment by marscher** [comment]
Thanks for bringing this up. I think the first option would be the way to implement this, as the ExternalFile class already implements to store the data inside the asdf file. 
We definitely need more metadata than the ExternalFile class encapsulates. This includes a reference time(stamp), MIME/data format, resolution, etc.
Storing raw data is prohibitively expensive for video data (hundreds of gigabytes for full-hd 10 minutes video). And (loss-less) image formats are also freely available. So I do not see any benefit from storing raw-data. It would only make things more complicated, as the user (or we as the api providers) would have to come up with a way to transform the raw data to a usable format. Even if the raw data (single frames) are available, we should store them encoded and decode on the fly for the sake of the weldx data format. Archiving data should consider storage efficiency IMO. If a ML algorithm needs lots of passes over the data it might be worth storing the extracted frames in a matrix/binary file, but this is out of the scope of weldx, right?

**Comment by CagtayFabry** [comment]
The benefit I see with a raw data structure would be that it could be easier to index individual frames (e.g. by timestamps) but in how far that is also possible for external files probably also depends on codecs used I guess

It is probably only feasible to implement for large video files if we had some kind of delayed/distributed loading mechanism into xarray/dask https://examples.dask.org/applications/image-processing.html

Providing the option for raw data should at least not be too difficult, I would leave it up to the users (and their files) to decide when that is reasonable.

Either way, my suggestion was to support both use cases but we can of course start with external files

**Comment by marscher** [comment]
If we introduce an extra layer to handle these time and or frame based indexing, it would be not any different if the data is "raw", in memory, or an external file. For time based data like videos, we could use opencv to extract frames, or ffmpeg directly.
But note, that one can easily blow the memory, if the video is a couple of minutes and the slice is too large :skull: 
I guess this is want you like to prevent by using this delayed loading mechanism. Would the dask array be populated, when an operation like `mean` etc. is used?

So lets go for the option to provide raw-data, and then derive this for special cases like defined image and video formats (we need). What do you think?

**Comment by CagtayFabry** [comment]
My proposal:
- first implement basic support for external files (with MIME metadata etc)
- after, add additional possibilities to store a custom time index alongside the file ( e.g. simply provide 'fps', 'pd.TimedeltaIndex' or full 'weldx.Time' with absolutetimes etc.)

After that we can easily add the raw data format

regarding the image processing with dask: the data should be kept distributed unless you explicitly load it on the client. So you should be able to run some form of image processing on a very large array and save it to a new file without ever loading the complete file into memory.
But I have so far only used it with different xarray structures and not images (which should work the same either way)

**Comment by marscher** [comment]
> 

That sounds reasonable :+1: 

Thanks for sharing the insight how dask is doing its work.

**Comment by marscher** [comment]
some interesting reads on videos and obtaining their individual frames:

1. https://github.com/dask/dask-image/issues/134
2. https://github.com/PyAV-Org/PyAV
3. https://docs.dask.org/en/latest/delayed.html
4. https://napari.org/tutorials/processing/dask.html
