### ISSUE TITLE
Raising errors for a (plain) warning for all libraries in an env

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#709]
Referring to pint.UnitStrippedWarning, which is **unconditionally** turned into an exception no matter where it arises. This may be a great way to debug things locally. Somehow it slipped into the main branch and breaks code outside of weldx.

**Comment by CagtayFabry** [comment]
Can you add some more context?
It breaks stuff on import? Install? 

afaik this was only added in the pytest section in `setup.cfg`, it would surprise me if it would have an effect outside of this context.

**Comment by marscher** [comment]
This snippet triggers the Warning, which is being raised.

``` python

import numpy as np
import weldx
import xarray as xr
vs = np.array(
    [1,2,3], dtype=float
)  * weldx.U_("cm/min")  # attached with unit
vd = np.arange(1, 3).astype(float)  # no unit

data = [xr.DataArray(np.zeros((2,3))) ] * 2

da = xr.concat(data, dim="s").assign_coords(vs=vs_, vd=vd_)
da.expand_dims(("vs", "vd"))
```

**Comment by marscher** [comment]
after upgrading my env, I cannot reproduce this any more.
