### ISSUE TITLE
`WeldxFile` doesn't raise `KeyError` on missing key

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#757]
When trying to access a non existing key from `WeldxFile`, `None` is returned instead of raising a  `KeyError`.
```python
from weldx import WeldxFile

with WeldxFile(tree={"key":"value"}, mode="rw") as wxf:
    print(wxf["key"])
    print(wxf["anything"])
# value
# None
```

Is this the intended behavior @marscher ?

**Comment by marscher** [comment]
Actually it should raise, I'll look into it.

**Comment by marscher** [comment]
WeldxFile derives (indirectly from MutableMapping, formely collections.abc.MutableMapping). Their implementation of get does not raise anymore, so I guess we directly want to extend the dict class.

**Comment by CagtayFabry** [comment]
ok great, I think raising makes more sense here as well.
It's not really high priority but good to know
