### ISSUE TITLE
Hide plotting cells in LCS tutorial

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#787]
Unfortunately, hiding cell inputs (but not the outputs) isn't as straightforward with cell tags as hoped (see #775). This should be fixed in the future, maybe when #745 is addressed. The cells of the LCS tutorial that should be hidden are already tagged with `"remove-input"`.

**Comment by CagtayFabry** [comment]
the `"remove-input"` tag works as intended now with the myst transition from https://github.com/BAMWelDX/weldx/pull/830

**Comment by marscher** [comment]
a nice :+1:
