### ISSUE TITLE
Shape validation in anyOf constructs causes problems

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#80]
In the current version of the TimeSeries schema, we have 3 options which types are supported. Only for one type (discrete values) it makes sense to validate the shape. The relevant implementation looks like this:

https://github.com/BAMWelDX/weldx/blob/ba94e7ed647ed7ad0e34ee4e4ed4b8de99dd7f45/weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml#L11-L79

The problem here is, that the validator   

https://github.com/BAMWelDX/weldx/blob/ba94e7ed647ed7ad0e34ee4e4ed4b8de99dd7f45/weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml#L72-L79

tries to access the `"time"` key of the current object, but neither constant value nor expressions have one. Therefore an `InvalidKeyError` is raised which causes a crash. Moving the discrete implementation to the end circumvents this since the execution of `anyOf` ends as soon as a match is found. However, this is not a fix but just a "cheat" ;) - It can probably be fixed by catching the error and raising a `ValidationError` instead.

**Comment by CagtayFabry** [comment]
agreed, `ValidationError` should hopefully give the expected outcome here. See #82
