### ISSUE TITLE
Enable usage of "description" tag in validators

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#81]
Currently, `description:` tags inside of a validator cause an error. Here is an example:

https://github.com/BAMWelDX/weldx/blob/ba94e7ed647ed7ad0e34ee4e4ed4b8de99dd7f45/weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml#L72-L79

Uncommenting line 73 and 74 will result in an exception. I think descriptions for validators might be nice to give some extra information about the purpose, especially if the shapes get a little bit fancier in case of the shape validator.

**Comment by CagtayFabry** [comment]
I think `description` only exists as a key on schema/object/property level right now? I don't know if this gets picked up by anything besides [sphinx-asdf](https://pypi.org/project/sphinx-asdf/) ?
Not sure what the advantage would be over a simple inline comments unless we would want the validator description show up on the generated docs (I don't think validators get this kind of treatment right now).
I would suggest keeping inline comments or moving the shape description to the object description.

**Comment by vhirtham** [comment]
The only advantage is, that it blends in with the rest of the schema documentation. Comments will do the trick too, but I thought it might be easy to just capture the tag and remove it from the tree. Anyways, it is not that important, we can close this issue. Just wanted to discuss it.
