### ISSUE TITLE
asdf-2.14.1 leads to a condition where weldx extension is found twice.

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#825]
This makes `get_weldx_extension()` fail, as the weldx extension is meant to be found only once. Eventually we register our extension in a legacy manner.
Downgrading to asdf-2.13 circumvents this problem.

**Comment by marscher** [comment]
It seems one `Extension` contains all converters and tags, and the other does only contain tags.

**Comment by marscher** [comment]
Note that I released a quick fix build for conda-forge pinning asdf to <2.14

**Comment by marscher** [comment]
xref conda-forge/weldx-feedstock#22

**Comment by marscher** [comment]
@CagtayFabry another interesting observation is that on asdf-2.13 the legacy flag of the extension is `False`, while in asdf-2.14 it is `True`. But I cannot spot this change in upstream extension handling... Note that even asdf's extension is a legacy on 2.14

Its weird :hurtrealbad:

**Comment by CagtayFabry** [comment]
> @CagtayFabry another interesting observation is that on asdf-2.13 the legacy flag of the extension is `False`, while in asdf-2.14 it is `True`. But I cannot spot this change in upstream extension handling... Note that even asdf's extension is a legacy on 2.14
> 
> Its weird :hurtrealbad:

that is indeed really weird, I suggest bringing this up in https://github.com/asdf-format/asdf/issues/1254 too and looking for clarification with the asdf devs on what is happening here

I have not followed the 2.14 release in depth so far

**Comment by marscher** [comment]
It looks like if you have an editable install (which we also do for our Github action pipeline), we get duplicated entry points.

**Comment by WilliamJamieson** [comment]
I think ASDF (thanks @braingram) may have fixed this bug in asdf-format/asdf#1260. Can you confirm that this resolves your bug? If so we will do a bugfix release ASAP for you.

**Comment by CagtayFabry** [comment]
> I think ASDF (thanks @braingram) may have fixed this bug in [asdf-format/asdf#1260](https://github.com/asdf-format/asdf/pull/1260). Can you confirm that this resolves your bug? If so we will do a bugfix release ASAP for you.

We will look into it, thank you for the heads up! @WilliamJamieson 🚀

**Comment by marscher** [comment]
@WilliamJamieson Thanks for providing this fix. It works like expected!

**Comment by marscher** [comment]
fixed upstream by asdf-format/asdf#1260
