### ISSUE TITLE
[docs] WeldxFile output in notebooks renders to IPython.display.JSON in jupyterhub environment

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#846]
This can only be shown in a Jupyter lab environment. So the selection of the output should be made aware, that it is contained in a Sphinx/non-interactive session in order to avoid this.

  
![image](https://user-images.githubusercontent.com/170287/215043978-df2eb6c0-c0e3-49cc-b669-b8fc05e2c5a0.png)

**Comment by CagtayFabry** [comment]
I think this is twofold:

first, this https://github.com/BAMWelDX/weldx/blob/ac3eda4a4ef015e4d34767a0b7db2f3c9e22182a/weldx/asdf/file.py#L918-L922
  should really be
  ```python
   def _ipython_display_(self): 
       # this will be called in Jupyter Lab, but not in a plain notebook. 
       from IPython.core.display import display 
  
       display(self.header(use_widgets=True, _interactive=_is_jupyterlab_session())) 
  ```

unfortunately, `_is_jupyterlab_session()` doesn't really work, at least not on the JupyterHub install

I haven't really found a nice way to implement `_is_jupyterlab_session()` correctly

**Comment by marscher** [comment]
I think there is no correct way to implement this jlab session detection reliably, because in theory there can be arbitrary frontends (historically). Of course right now there is only jlab or jupyter notebook (the later has multiple guis).

We could monkey patch the method for Sphinx to force _interactive to be false. Or set an environment variable within the Sphinx build which can the be checked in the implementation. Both solutions are not elegant, but they'd do the job.

**Comment by CagtayFabry** [comment]
> 

I like the monkey patching approach you mentioned, that shouldn't be to difficult I hope?

**Comment by marscher** [comment]
It is not possible to patch this via the Sphinx config, because the kernel manager involved in executing the notebooks is a separate process which does not ever import this config.

**Comment by marscher** [comment]
On Windows? On Linux I gave it a shot and it used the widgets correctly.

**Comment by CagtayFabry** [comment]
> On Windows? On Linux I gave it a shot and it used the widgets correctly.

Interesting, I was logging into the Lab-JupyterHub from Windows for testing
