### ISSUE TITLE
pypi project description is gone

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#852]
```

Project description

The author of this package has not provided a project description
```

So something is wrong either with our pyproject.toml or with PyPIs handling of the same.

**Comment by marscher** [comment]
readme = {file = "README.rst", content-type="text/x-rst"}

**Comment by marscher** [comment]
For now I'd just fix this via the project settings in PyPI, but I'm no maintainer. For the next release, we should switch to README.md

**Comment by CagtayFabry** [comment]
see #851 :)

I will add you as maintainer on pypi @marscher , I could't find how to fix this manually

**Comment by marscher** [comment]
Thanks! There is no solution anymore. Back in the day one could upload new source archive (different format) and delete the faulty one.
