### ISSUE TITLE
Validation bug in anyOf/oneOf structures

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#88]
The wx_shape validator causes problems in a `oneOf` or `anyOf` block. Seems like the validator, even if explicitly defined for a single object, is validated against all other objects too. We need to investigate why. Also, a validation in one of the objects inside the `oneOf` block will cause a crash, even though there might be another valid option in the `oneOf` block. This, and maybe also the first problem, are probably ASDF bugs. Write a minimal example and submit bug reports.

**Comment by CagtayFabry** [comment]
Maybe this happens because we `raise ValidationError` instead of correctly yielding errors as expected by asdf

**Comment by CagtayFabry** [comment]
Fixed with #89
