### ISSUE TITLE
Add support to create Coordinate Systems from homogeneous transformation matrices

### ISSUE THREAD

**Issue by mbwinkler** [BAMWelDX/weldx#948]
Add a method to `CoordinateSystemManager` to add a new CoordinateSystem by using homogeneous transformation matrices as predominately used with `open3d.`

**Homogeneous Transformation from Coordinate System A to B**

```math
B = T_{AB} \times A = 
\left[ \begin{matrix}
r_{11} & r_{12} & r_{13} & t_{1}\\
r_{21} & r_{23} & r_{23} & t_{2}\\
r_{31} & r_{32} & r_{33} & t_{3}\\
0 & 0 & 0 & 0\\
\end{matrix}\right] \times 
\left[\begin{matrix}
A_{x} \\
A_{y}\\
A_{z} \\
1\\
\end{matrix}\right]
= \left[ \begin{matrix}
R & t \\
0 & 1\\
\end{matrix}\right] \times 
\left[ \begin{matrix}
A  \\
1\\
\end{matrix}\right] 
```

the transformation matrix is made up of the `Rotation R` and the `Translation t`.

Therefore, to adapt to the current code, the `orientation` and `coordinates` during `LocalCoordinateSystem` construction can be substituted using `homogenous_transformation` and `unit` (unit in which the translation part is given. e.g. "mm")

**Comment by CagtayFabry** [comment]
A good idea!
I suggest implementing this as `CoordinateSystemManager.create_cs_from_homtransform` (to keep the method name somewhat short)

Let me know if you would like any help with this 👍
